### PR TITLE
Fix Kafka test setup issue by adding wait period

### PR DESCRIPTION
**Pull request by yongtang**
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
The kafka test issue has been fixed. The issue was that GitHub Actions changes to ipv6 and `localhost` domain is having trouble to map to 127.0.0.1.

The pulsar is still having issues. I assume this might be related to ipv6 vs ipv4 as well.

/cc @kvignesh1420 @terrytangyuan @burgerkingeater

**Review by terrytangyuan — APPROVED** [review]

**Comment by yongtang** [comment]
@BewareMyPower the test setup on pulsar is failing and is likely caused by ipv4 vs ipv6. Do you know if there is a way to only bind to ipv4 for pulsar?

**Comment by BewareMyPower** [comment]
I'll take a look soon. BTW, could you try to configure `advertisedAddress=127.0.0.1` in `conf/standalone.conf` using `sed` command?

**Review by burgerkingeater — APPROVED** [review]

**Review by kvignesh1420 — APPROVED** [review]
@yongtang seems like the Kafka, Pulsar issues are resolved but some fs based issues are popping up randomly. However, based on the purpose of this PR, we can merge it.

**Comment by yongtang** [comment]
@kvignesh1420 Thanks for the latest commit fix! As the master branch is failing I will merge this PR for now. 

The pulsar is ok on macOS though it still fails on Linux, likely due to ipv4/ipv6 (as was mentioned earlier). The PR disabled pulsar on Linux for now. I will open an issue to track pulsar on linux test.

**Pull request merged**
