### PR TITLE
Adding memcached file system and cache to gstpufs

### PR DESCRIPTION
**Pull request by marioecd**
Active PR to merge the memcached file system and its cache into the gstpufs subdir

### CODE REVIEW

**Comment by yongtang** [comment]
@marioecd  The CI error was caused by two issues, one is the windows python version (due to GitHub CI's upgrade), the other one requires a fix up of libmemecached.BUILD file to include some hashkit dependencies.

I think I can get those issues addressed. Let me update the nightly branch shortly.

**Comment by yongtang** [comment]
@marioecd Actually, I think I can just merge this one and create a follow up commit to address the issue mentioned. This can avoid the rebase on your side again.

**Comment by yongtang** [comment]
@marioecd The PR has been merged in nightly branch now:

https://github.com/tensorflow/io/commits/nightly

I updated the nightly branch on top of that. Now all build should be pass on macOS/linux/windows.

I also fast forward nightly branch so that it matches latest master. If you create new PRs for nightly branch in the future you may need to rebase again.

I understand this is not ideal and sorry for you inconvenience. Though this is the limitation of TF's recent API C++ API change.

We plan to update the master branch to a new version of TF once TF 2.3.0rc0 (release candidate 0) is out. After that I think you can just create PR against master, without the need to rebase against nightly that might be falling behind.

**Comment by marioecd** [comment]
Thanks for the help! I actually think I may not need to add another new PR until TF 2.3 is out.

**Pull request merged**
