### PR TITLE
Add Ogg support for AudioIOTensor

### LINKED ISSUE #650: Support ogg file format
This issue is opened to track the progress for ogg audio format.

In tensorflow-io, we have the support for various audio format for FFmpeg. However, FFmpeg lacks fine control of the seek ability.

The plan is to support a small widely used audio format in `IOTensor.from_audio` natively (not through FFmpeg). And FFmpeg will only be a fallback method for user to use (without fine control of seek).

At the moment WAV file is supported, through we can certainly support ogg in `from_audio`. We could even detect format internally.

So the usage would be that user can feed wav or ogg into `from_audio` without any modification of the code. .

/cc @faroit

### PR DESCRIPTION
**Pull request by yongtang**
This PR adds Ogg support for `IOTensor.from_audio`. No API updates as it automatically reroute to Ogg if file type support.

This PR fixes #650.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
This PR is ready for review.

/cc @faroit

**Comment by faroit** [comment]
will test that later

**Comment by faroit** [comment]
@yongtang I am currently unable to build locally. Is an OS X build for testing?

**Comment by yongtang** [comment]
@faroit One way is to merge this PR, then the nightly build for macOS and Linux are automatically released.

ping @terrytangyuan @BryanCutler

**Comment by yongtang** [comment]
@faroit The latest nightly build of `0.10.0.dev2273`:

https://pypi.org/project/tensorflow-io-nightly/0.10.0.dev2273/

should have the ogg support. Let me know if you run into any issues.

**Comment by faroit** [comment]
works fine. Performance could be a bit better, though.
benchmark_tf

**Pull request merged**
