### PR TITLE
handle missing dependencies while benchmarking

### PR DESCRIPTION
**Pull request by kvignesh1420**
This PR is a follow up of https://github.com/tensorflow/io/pull/1269 and handles the missing dependencies while benchmarking.

### CODE REVIEW

**Comment by kvignesh1420** [comment]
@yongtang the store-benchmark phase is failing due to the absence of a `gh-pages` branch in our repo. Can you please create it? 
```
Error: Command 'git' failed with args '-c user.name=github-action-benchmark -c user.email=github@users.noreply.github.com -c http.https://github.com/.extraheader= fetch origin gh-pages:gh-pages': fatal: couldn't find remote ref gh-pages
```

**Comment by yongtang** [comment]
@kvignesh1420 A branch `gh-pages` has been created. Let me know if this works.

**Comment by kvignesh1420** [comment]
@yongtang now the action is working fine. However, the action needs a `PERSONAL_ACCESS_TOKEN` to push the changes to the `gh-pages` branch. Steps are as follows:

```
Go to your user settings page
Enter 'Developer settings' tab
Enter 'Personal access tokens' tab
Click 'Generate new token' and enter your favorite token name
Check repo scope for git push and click 'Generate token' at bottom
Go to your repository settings page
Enter 'Secrets' tab
Create new PERSONAL_GITHUB_TOKEN secret with a generated token string
```

Reference: [Benchmark charts](https://github.com/rhysd/github-action-benchmark#charts-on-github-pages-1)

**Comment by yongtang** [comment]
@kvignesh1420 Token has been added.

**Comment by kvignesh1420** [comment]
@yongtang what is the name of the `secret` that you created for the token?

**Comment by yongtang** [comment]
@kvignesh1420 If you are looking to do a git push on GitHub Actions, maybe you can try `GITHUB_TOKEN` secret which is automatically added by GitHub Actions:

https://docs.github.com/en/actions/reference/authentication-in-a-workflow

You can see some examples like:
https://github.com/coredns/coredns/blob/0a6100048d3b8abaac1e5a3b0b9d08d4576920ce/.github/workflows/go.tidy.yml#L31-L35

**Comment by kvignesh1420** [comment]
@yongtang I am constantly observing this issue:
```
Switched to branch 'gh-pages'
remote: Permission to tensorflow/io.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/tensorflow/io.git/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```
Do we need additional permissions?

**Comment by yongtang** [comment]
@kvignesh1420 Ah, I remember in the past GitHub may not pass secrets to PRs for security reasons, as anyone would be possible to open a PR and trigger an action (with secret). For that I tends to believe only code already merged can work.

Can you try with your forked repo and see if it can be pushed to your forked repo? If that passes we can merge this PR and see how everything goes.

**Comment by kvignesh1420** [comment]
@yongtang I tried merging my branch with my forked master and it works:

image

So, it should work after merging with this PR as well.

**Comment by yongtang** [comment]
@kvignesh1420 Thanks. Let's merge and see how everything goes.

**Pull request merged**
