### PR TITLE
Update to use https for http file system test also registers https file system

### PR DESCRIPTION
**Pull request by yongtang**
The http test is failing as apache switched to use https for license page.

This PR makes adjustment to fix the issue.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by kvignesh1420 — APPROVED** [review]
LGTM

**Review by terrytangyuan — APPROVED** [review]

**Comment by vnvo2409** [comment]
@yongtang Could you also change the example in `README.md` to `https` ? Thank you !

**Comment by yongtang** [comment]
@vnvo2409 The PR has been updated.

**Review by vnvo2409 — APPROVED** [review]
Thank you!

**Pull request merged**
