### PR TITLE
Fix several issues in avro_dataset_ops.py

### PR DESCRIPTION
**Pull request by burgerkingeater**
1. fix wrong tf APIs
2. rename check_none to check_not_empty
3. implement base class's abstract method in _AvroDataset
4. fix FixedLenFeature shape check

### CODE REVIEW

**Comment by yongtang** [comment]
@burgerkingeater I think the CLA issue is caused by your first commit where you use the `Cheng Ren <chren@xxx.biz>`.

Can you update your commit to set the author to the email you use for CLA? (the second commit is ok, just the first commit)

You can use the following to update:
```
% git rebase -I HEAD~2

# change the line with the first commit 86a2dfef004f0bf5df163c69d9d28689ddc56e2c from "pick" to "e"

# then use the following to update:
git commit --amend -s --reset-author

git rebase --continue

# finally push with -f
git push -f origin tf-io-oss-master-fix_avro_dataset_ops
```

**Comment by burgerkingeater** [comment]
@yongtang  thanks, updated.

**Comment by yongtang** [comment]
@burgerkingeater Looks like the Linux test is flaky. Can you try touch the commit and push, to trigger GitHub again?

**Comment by burgerkingeater** [comment]
@yongtang updated

**Comment by yongtang** [comment]
@burgerkingeater It looks ok for now. Though It is a surprise some of the incorrect API usage still passes tests. If they are orphaned code they should be removed. Otherwise additional tests could be added to cover.

**Pull request merged**
