### PR TITLE
Dicom tuto plus tags

### PR DESCRIPTION
**Pull request by ZWael**
following #1493
#suggesting a new a new subchapter for working with dicom tags in tfio
#"Decode DICOM Metadata and working with Tags "
#
my tuto file is named dicom.ipynb as suggested by @yongtang

### CODE REVIEW

**Review by yongtang — APPROVED** [review]

**Comment by yongtang** [comment]
@ZWael Can you try to see if you can rebase the PR to trigger the GitHub Actions? I tried to relaunch it from UI though it encountered some issues. I assume a rebase of the PR will resolve the issue.

**Comment by ZWael** [comment]
Hi @yongtang  
I tried this tuto https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request
all works fin until the final push step
I have this :
fatal: The current branch Dicom_tuto_plus_tags has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin Dicom_tuto_plus_tags

using the suggested command git push --set-upstream origin Dicom_tuto_plus_tags i have this issue 

 ! [rejected]        Dicom_tuto_plus_tags -> Dicom_tuto_plus_tags (non-fast-forward)
error: failed to push some refs to 'https://github.com/ZWael/io.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by yongtang** [comment]
@ZWael Not sure about the steps you used, but I think you can try the following (fresh new one):

```
git clone https://github.com/ZWael/io.git
cd io
git config user.name "..."
git config user.email "..."
git checkout Dicom_tuto_plus_tags
git commit -s --allow-empty
git push origin Dicom_tuto_plus_tags
```

That will create an empty commit that can trigger the GItHub Actions. Maybe you can give it a try?

**Comment by ZWael** [comment]
@yongtang  
Thanks for the code, it worked.
now the workflow is awaiting approval

**Comment by ZWael** [comment]
Hi @yongtang 
do you have an idea how to solve the linting issue ?

**Comment by yongtang** [comment]
@ZWael If you run the following command then the files will be automatically formatted:
````
python3 --version
python3 -m pip install dataclasses
python3 -m pip install setuptools
python3 -m pip install -U git+https://github.com/tensorflow/docs
find docs -name '*.ipynb' | xargs python3 -m tensorflow_docs.tools.nbfmt
````

After that you can run `git diff` to see the changes.

**Comment by ZWael** [comment]
Hi @yongtang, thank you a lot for your help and availability 
I was not able to run the code in my windows machine (I think  ```find```  and ```| xargs``` have to be changed ) and i have the same issue with the anaconda shell 
but with a linux machine i run this 
````
git clone https://github.com/ZWael/io.git
cd io
git checkout Dicom_tuto_plus_tags
python3 --version
python3 -m pip install dataclasses
python3 -m pip install setuptools
python3 -m pip install -U git+https://github.com/tensorflow/docs
find docs -name '*.ipynb' | xargs python3 -m tensorflow_docs.tools.nbfmt
git diff
```
should make a new commit ? 


the git diff result :

diff --git a/docs/tutorials/dicom.ipynb b/docs/tutorials/dicom.ipynb
index fd3ea52..026e49b 100644
--- a/docs/tutorials/dicom.ipynb
+++ b/docs/tutorials/dicom.ipynb
@@ -1,20 +1,4 @@
 {
-  "nbformat": 4,
-  "nbformat_minor": 0,
-  "metadata": {
-    "colab": {
-      "name": "dicom.ipynb",
-      "provenance": [],
-      "collapsed_sections": [
-        "Tce3stUlHN0L"
-      ],
-      "toc_visible": true
-    },
-    "kernelspec": {
-      "display_name": "Python 3",
-      "name": "python3"
-    }
-  },
   "cells": [
     {
       "cell_type": "markdown",
@@ -27,9 +11,12 @@
     },
     {
       "cell_type": "code",
+      "execution_count": null,
       "metadata": {
+        "cellView": "form",
         "id": "tuOe1ymfHZPu"
       },
+      "outputs": [],
       "source": [
         "#@title Licensed under the Apache License, Version 2.0 (the \"License\");\n",
         "# you may not use this file except in compliance with the License.\n",
@@ -42,9 +29,7 @@
         "# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
         "# See the License for the specific language governing permissions and\n",
         "# limitations under the License."
-      ],
-      "execution_count": null,
-      "outputs": []
+      ]
     },
     {
       "cell_type": "markdown",
@@ -121,15 +106,15 @@
     },
     {
       "cell_type": "code",
+      "execution_count": null,
       "metadata": {
         "id": "Tu01THzWcE-J"
       },
+      "outputs": [],
       "source": [
         "!curl -OL https://github.com/tensorflow/io/raw/master/docs/tutorials/dicom/dicom_00000001_000.dcm\n",
         "!ls -l dicom_00000001_000.dcm"
-      ],
-      "execution_count": null,
-      "outputs": []
+      ]
     },
     {
       "cell_type": "markdown",
@@ -142,29 +127,29 @@
     },
     {
       "cell_type": "code",
+      "execution_count": null,
       "metadata": {
         "id": "NwL3fEMQuZrk"
       },
+      "outputs": [],
       "source": [
         "try:\n",
         "  # Use the Colab's preinstalled TensorFlow 2.x\n",
         "  %tensorflow_version 2.x \n",
         "except:\n",
         "  pass"
-      ],
-      "execution_count": null,
-      "outputs": []
+      ]
     },
     {
       "cell_type": "code",
+      "execution_count": null,
       "metadata": {
         "id": "uUDYyMZRfkX4"
       },
+      "outputs": [],
       "source": [
         "!pip install tensorflow-io"
-      ],
-      "execution_count": null,
-      "outputs": []
+      ]
     },
     {
       "cell_type": "markdown",
@@ -177,23 +162,25 @@
     },
     {
       "cell_type": "code",
+      "execution_count": null,
       "metadata": {
         "id": "YUj0878jPyz7"
       },
+      "outputs": [],
       "source": [
         "import matplotlib.pyplot as plt\n",
         "import numpy as np\n",
         "\n",
         "import tensorflow as tf"
-      ],
-      "execution_count": null,
-      "outputs": []
+      ]
     },
     {
       "cell_type": "code",
+      "execution_count": null,
       "metadata": {
         "id": "zK7IEukfuUuF"
       },
+      "outputs": [],
       "source": [
         "import tensorflow_io as tfio\n",
         "\n",
@@ -211,9 +198,7 @@
         "axes[0].set_title('image')\n",
         "axes[1].imshow(np.squeeze(lossy_image.numpy()), cmap='gray')\n",
         "axes[1].set_title('lossy image');"
-      ],
-      "execution_count": null,
-      "outputs": []
+      ]
     },
     {
       "cell_type": "markdown",
@@ -235,40 +220,40 @@
     },
     {
       "cell_type": "code",
+      "execution_count": null,
       "metadata": {
         "id": "OqHkXwF0oI3L"
       },
+      "outputs": [],
       "source": [
         "tag_id = tfio.image.dicom_tags.PatientsAge\n",
         "tag_value = tfio.image.decode_dicom_data(image_bytes,tag_id)\n",
         "print(tag_value)"
-      ],
-      "execution_count": null,
-      "outputs": []
+      ]
     },
     {
       "cell_type": "code",
+      "execution_count": null,
       "metadata": {
         "id": "J2wZ-7OcoPPs"
       },
+      "outputs": [],
       "source": [
         "print(f\"PatientsAge : {tag_value.numpy().decode('UTF-8')}\")"
-      ],
-      "execution_count": null,
-      "outputs": []
+      ]
     },
     {
       "cell_type": "code",
+      "execution_count": null,
       "metadata": {
         "id": "Ce6ymbskoTOe"
       },
+      "outputs": [],
       "source": [
         "tag_id = tfio.image.dicom_tags.PatientsSex\n",
         "tag_value = tfio.image.decode_dicom_data(image_bytes,tag_id)\n",
         "print(f\"PatientsSex : {tag_value.numpy().decode('UTF-8')}\")"
-      ],
-      "execution_count": null,
-      "outputs": []
+      ]
     },
     {
       "cell_type": "markdown",
@@ -352,5 +337,20 @@
         "limitations under the License."
       ]
     }
-  ]
-}
\ No newline at end of file
+  ],
+  "metadata": {
+    "colab": {
+      "collapsed_sections": [
+        "Tce3stUlHN0L"
+      ],
+      "name": "dicom.ipynb",
+      "toc_visible": true
+    },
+    "kernelspec": {
+      "display_name": "Python 3",
+      "name": "python3"
+    }
+  },
+  "nbformat": 4,
+  "nbformat_minor": 0
+}
(END)
         "limitations under the License."
       ]
     }
-  ]
-}
\ No newline at end of file
+  ],
+  "metadata": {
+    "colab": {
+      "collapsed_sections": [
+        "Tce3stUlHN0L"
+      ],
+      "name": "dicom.ipynb",
+      "toc_visible": true
+    },
+    "kernelspec": {
+      "display_name": "Python 3",
+      "name": "python3"
+    }
+  },
+  "nbformat": 4,
+  "nbformat_minor": 0
+}
(END)
         "limitations under the License."
       ]
     }
-  ]
-}
\ No newline at end of file
+  ],
+  "metadata": {
+    "colab": {
+      "collapsed_sections": [
+        "Tce3stUlHN0L"
+      ],
+      "name": "dicom.ipynb",
+      "toc_visible": true
+    },
+    "kernelspec": {
+      "display_name": "Python 3",
+      "name": "python3"
+    }
+  },
+  "nbformat": 4,
+  "nbformat_minor": 0
+}

**Comment by yongtang** [comment]
@ZWael Yes you can add a new commit to carry the diff. That will solve the lint errors.

**Comment by ZWael** [comment]
thanks 
Done

**Comment by ZWael** [comment]
Hi @yongtang,
You don't have write access ?

**Comment by yongtang** [comment]
cc @MarkDaoust  @tensorflow/docs-team to take a look.

**Review by kvignesh1420 — APPROVED** [review]

**Comment by kvignesh1420** [comment]
cc: @MarkDaoust @tensorflow/docs-team gentle ping.

**Review by MarkDaoust — APPROVED** [review]
LGTM.

**Comment by kvignesh1420** [comment]
Thanks @ZWael

**Comment by ZWael** [comment]
Happy and honored to contribute

**Comment by ZWael** [comment]
hello everyone @yongtang @MarkDaoust @kvignesh1420 
I noticed that the new sections "Decode DICOM Metadata and working with Tags" .. figures on the github repo but not in the web page "https://www.tensorflow.org/io/tutorials/dicom"
is it ok ?

**Comment by markmcd** [comment]
> I noticed that the new sections "Decode DICOM Metadata and working with Tags" .. figures on the github repo but not in the web page "https://www.tensorflow.org/io/tutorials/dicom" is it ok ?

I'll get the doc update pipeline running. It's a holiday week in the US but hopefully we can get it up in the next day or two.

**Comment by MarkDaoust** [comment]
Dicom should be updated soon, 

But these two are failing:

https://github.com/tensorflow/io/issues/1568
https://github.com/tensorflow/io/issues/1569

**Comment by markmcd** [comment]
Most of the tfio docs are now updated, except as noted by Mark.

**Pull request merged**
