### PR TITLE
Adding external dependency on libmemcached to gstpufs

### PR DESCRIPTION
**Pull request by marioecd**
gstpufs will run a memcached file block cache that has an external dependency on libmemcached. This PR adds memcached_dao_interface and makes sure that it can build with the external dependency on libmemcached.

### CODE REVIEW

**Comment by marioecd** [comment]
Currently some checks are failing due to unrelated build-break from tfio "no such package '@speexdsp//'""

**Comment by yongtang** [comment]
@marioecd I have cherry-picked PR #944 into the nightly branch. if you update and rebase the GitHub CI issue will be resolved.

**Comment by marioecd** [comment]
Thanks. Done. This PR is now hitting a MacOS issue and a bazel windows issue. I am targeting this for Linux and I don't have the setup to debug and maintain MacOS and Windows environment for this. Is there a way I could disconnect this target from MacOS and windows dependents and checks?

**Comment by marioecd** [comment]
@libmemcached//:libmemcached fails in MacOS, eventhough it is ok in linux. This library that I am adding is going to run in linux only so macos shouldn't really depend on it.

**Comment by marioecd** [comment]
Ok, I've just tried moving gstpufs out of conditions:darwin to see if the MacOS check is skipped. Will check the tests.

**Comment by yongtang** [comment]
@marioecd Sorry for the late reply. I have been quite occupied today. I will take a look tomorrow and see if I can help get the build  failure addressed.

**Comment by marioecd** [comment]
No problem. Thanks. There is only 3 checks failing:
- googlebot waiting for approval
- windows bazel: https://github.com/tensorflow/io/issues/945 seems unrelated to this PR.
- test macos 3.7 seems also unrelated to this PR. It had passed on my previous commits.

**Comment by yongtang** [comment]
@marioecd The google bot check is likely due to the first commit in your PR is not associated with  your email. It is `Cloud TPU <no-reply@google.com>`.

You can change the email to your email with the following:
```
git rebase -i HEAD~5
# change the first commit from "pick" to "e",
# exit editor, and you could modify the history with:
git commit -s --amend --reset-author
# finally continue the rebase:
git rebase --continue
```


Or, if the commit is from another author internally in google, you can confirm here and I can override the google bot.

**Comment by marioecd** [comment]
The commit is mine. I performed the amend but the check still failed. This is what I did:

Adding memcached dao interface and libmemcached dep.

PiperOrigin-RevId: 309996591
Signed-off-by: **marioecd <marioecd@google.com>**

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# interactive rebase in progress; onto 4c80010
# Last command done (1 command done):
#    edit 6d659f1 Internal change
# Next commands to do (4 remaining commands):
#    pick cb44cfc Adding references to the dependencies on libmemcached.
#    pick 13025ad Avoid MacOS: move gstpufs out of darwin condition.
# You are currently rebasing branch 'nightly' on '4c80010'.
#
# Changes to be committed:
#       modified:   tensorflow_io/core/kernels/gstpufs/BUILD
#       new file:   tensorflow_io/core/kernels/gstpufs/memcached_dao_interface.h
#       new file:   tensorflow_io/core/kernels/gstpufs/workspace.bzl
#       new file:   third_party/expand_template.bzl
#       new file:   third_party/libmemcached.BUILD
#       new file:   third_party/libmemcached.mem_config.h
#

**Comment by yongtang** [comment]
@marioecd I think your last merge commit 0bd3077e9e1d702fbc8e530c95464aecb8354d13 makes the history longer and changed the branch point, so `git rebase` was confused.

Not easy to do a in-place fix with merge commit in place, but you probably could just create a new branch and cherry-pick the 5 commits, similar to https://github.com/tensorflow/io/pull/919#issuecomment-620151645

**Pull request closed without merging**
