### PR TITLE
Reformat the codebase with lint

### PR DESCRIPTION
**Pull request by burgerkingeater**
run `bazel run //tools/lint:lint`(https://github.com/tensorflow/io#lint) to reformat the codebase.

### CODE REVIEW

**Comment by yongtang** [comment]
@burgerkingeater The build failure is caused by the header file re-ordering, which exposes some missing declarations in header file itself. You can fix them with the following patch:
```diff
diff --git a/tensorflow_io/arrow/kernels/arrow_kernels.h b/tensorflow_io/arrow/kernels/arrow_kernels.h
index b36b8f7..2ad9e57 100644
--- a/tensorflow_io/arrow/kernels/arrow_kernels.h
+++ b/tensorflow_io/arrow/kernels/arrow_kernels.h
@@ -20,6 +20,7 @@ limitations under the License.
 #include "arrow/io/api.h"
 #include "arrow/type.h"
 #include "parquet/windows_compatibility.h"
+#include "tensorflow/core/framework/op_kernel.h"
 #include "tensorflow_io/core/kernels/io_stream.h"
 
 namespace tensorflow {
diff --git a/tensorflow_io/arrow/kernels/arrow_util.h b/tensorflow_io/arrow/kernels/arrow_util.h
index bf99189..9d2bc03 100644
--- a/tensorflow_io/arrow/kernels/arrow_util.h
+++ b/tensorflow_io/arrow/kernels/arrow_util.h
@@ -16,6 +16,13 @@ limitations under the License.
 #ifndef TENSORFLOW_IO_ARROW_UTIL_H_
 #define TENSORFLOW_IO_ARROW_UTIL_H_
 
+#include "arrow/api.h"
+#include "arrow/ipc/api.h"
+#include "arrow/util/io_util.h"
+#include "tensorflow/core/framework/tensor.h"
+#include "tensorflow/core/lib/core/errors.h"
+#include "tensorflow/core/lib/core/status.h"
+
 namespace tensorflow {
 
 // Forward declaration
```

Once the patch is applied then the build and test should pass.

**Comment by burgerkingeater** [comment]
@yongtang thanks updated, but i wonder why there's such huge formatting change needed? won't lint fail?

**Comment by yongtang** [comment]
@burgerkingeater  clang has not been enforced yet in GitHub CI, appending clang to the following line will enforce it:
https://github.com/tensorflow/io/blob/master/.github/workflows/build.yml#L28

**Comment by burgerkingeater** [comment]
@yongtang i see, so after this PR is merged, probably we can consider enforcing the clang check?

**Comment by yongtang** [comment]
@burgerkingeater definitely. PR to enable the clang checks is welcomed 👍

**Pull request merged**
