### PR TITLE
Add `ref` and `amin` argument in `dbscale`

### PR DESCRIPTION
**Pull request by awsaf49**
This PR will add two parameters `ref` and `amin` in `tfio.audio.dbscale()`, similar to **librosa** `power_to_db` function.
* `amin` will avoid $-inf$ for zero inputs
* `ref` will provide more flexibility as many user use `np.max` as ref.

### CODE REVIEW

**Comment by awsaf49** [comment]
cc: @terrytangyuan

**Review by terrytangyuan — COMMENTED** [review]
Could you add some tests?

**Comment by awsaf49** [comment]
Sure, I am working on it.

**Comment by awsaf49** [comment]
@terrytangyuan I have added the tests, please approve the workflow.

**Comment by awsaf49** [comment]
@terrytangyuan there was linting issue with `black`, I have fixed it. But there is also error with `Blazw Windows`. But can't seem to figure out the reason.

**Comment by yongtang** [comment]
@awsaf49  @terrytangyuan  the windows failure is unrelated - you can ignore it for now.

**Comment by awsaf49** [comment]
@yongtang In that case, I think we're good to go.......

**Review by yongtang — APPROVED** [review]

**Pull request merged**
