### PR TITLE
github action to push docker images to registry

### PR DESCRIPTION
**Pull request by kvignesh1420**
This PR addresses the issue: https://github.com/tensorflow/io/issues/1087 by adding a GitHub action to test and push the docker images to the registry.

The docker image testing step has been migrated from the `linux-test` job to the new `docker-release` job.

### CODE REVIEW

**Comment by kvignesh1420** [comment]
@yongtang can you please create the GitHub secrets with the username and password of the `tfsigio` account?

the secrets are used in the actions in the following fashion:
- `${{ secrets.DOCKER_USERNAME }}` 
- `${{ secrets.DOCKER_PASSWORD }}`

**Comment by yongtang** [comment]
Thanks @kvignesh1420. I added `${{ secrets.DOCKER_PASSWORD }}` to the configuration. For `DOCKER_USERNAME` I think you can just replace it with `tfsigio` directly.

**Comment by kvignesh1420** [comment]
@yongtang I modified the username. The expected behaviour is to test and push the images once the PR (and upcoming PR's) have been approved and committed. 

Also can we please delete the `tfiocontainer` account in docker? might cause confusion to users.

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
