### PR TITLE
[docs] add mongodb tutorial

### PR DESCRIPTION
**Pull request by kvignesh1420**
This PR adds a tutorial for the `MongoDBIODataset` APIs.

### CODE REVIEW

**Review by MarkDaoust — APPROVED** [review]
Thanks, this looks good.

I just made 2 tiny changes:

1. I need a sudo on that `apt install` 
2. when you create or modify a tf.data.Dataset it helps to display it so people can see the structure and dtyps.

**Comment by kvignesh1420** [comment]
Thanks @MarkDaoust

**Comment by kvignesh1420** [comment]
cc: @yongtang PTAL

**Review by yongtang — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
