### PR TITLE
Disable s3 macOS for now as docker is not working on GitHub Actions for macOS

### PR DESCRIPTION
**Pull request by yongtang**
This PR disable s3 macOS for now as docker is not working on GitHub Actions for macOS

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by burgerkingeater — APPROVED** [review]
LGTM

**Review by terrytangyuan — APPROVED** [review]

**Review by kvignesh1420 — COMMENTED** [review]
@yongtang do you think we should raise this issue with the `github-actions` team?

**Comment by yongtang** [comment]
@kvignesh1420  The issue is with `actions-setup-docker` (https://github.com/docker-practice/actions-setup-docker):
```
Run docker-practice/actions-setup-docker@v1
install docker
  /usr/local/bin/brew cask install docker
  Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
  Error: Error: The process '/usr/local/bin/brew' failed with exit code 1
```
which I assume a simple change will be enough. Though I am not very familiar with how the code works.

**Comment by kvignesh1420** [comment]
@yongtang I think this is the step in their code-base which is erroring out:
https://github.com/docker-practice/actions-setup-docker/blob/330bf23fad1196d9badb2f099414bf5c0a23e1b5/lib/setup-docker.js#L122

Will raise an issue in their repo.

**Pull request merged**
