### PR TITLE
Update README.md and RELEASE.md, to prepare 0.24.0 release.

### PR DESCRIPTION
**Pull request by yongtang**
Update README.md and RELEASE.md, to prepare 0.24.0 release, and bump to TF 2.8.0.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]

**Review by kvignesh1420 — APPROVED** [review]
Thanks @yongtang

**Review by kvignesh1420 — COMMENTED** [review]
@yongtang I think the macos failures are due to issues with `pip` (reference: https://github.com/readthedocs/readthedocs.org/issues/8864). Can we pin `pip==21.3.1` as of now so that the CI job passes?

**Comment by yongtang** [comment]
Thanks @kvignesh1420 for the hint!

**Comment by yongtang** [comment]
Binaries available:
```bash
$ sha256sum tensorflow*.whl
d1d9a6401f674003b13564d716137bd150e2867e2e4156e3c60e22d391481649  tensorflow_io-0.24.0-cp310-cp310-macosx_10_14_x86_64.whl
02a7ff1c1f0d0e3725e0c140e87e47b83e06d94093991a5951769d058a274bc6  tensorflow_io-0.24.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
532ce560a16662c606c4c2866792c2cf02e6f7ecc7a45e678e0fb04f58293fb6  tensorflow_io-0.24.0-cp310-cp310-win_amd64.whl
6b677f7a4796241ae8502c1e26960dbb94b9244200920c56d47f526998b37d32  tensorflow_io-0.24.0-cp37-cp37m-macosx_10_14_x86_64.whl
24d5845f56307d88c234337baa30d7a2311bda1261846c81897932e3d9d332b2  tensorflow_io-0.24.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
07b9fa4aa0772d4c7b83b49b4a28222253c96b1b4287c5a29dcf75394a7a55f3  tensorflow_io-0.24.0-cp37-cp37m-win_amd64.whl
2be92fd56f81a5e72af4d778d5b3bea73ee9e384b67ca6a3ddc992f8909b1ada  tensorflow_io-0.24.0-cp38-cp38-macosx_10_14_x86_64.whl
0b86365efc428c65ddfc924ba7fbf7fa0e59f511e129ee5dab6d312860e3c881  tensorflow_io-0.24.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
e7fa455503a5bd1d5e3febf584eeb9854bc9ef7764a2e2a9745144716737af5c  tensorflow_io-0.24.0-cp38-cp38-win_amd64.whl
ac5a247c217b9a6619d7aaf74e2c9e911cffab35a1b74cf4164a14069ce56bf5  tensorflow_io-0.24.0-cp39-cp39-macosx_10_14_x86_64.whl
b69651367d47b1215e8efdf53c271f7eb3cf54b9f12d5ef12b988a3aaa62940e  tensorflow_io-0.24.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
709355a59c35cf7eb26507dfc2c918648c69214647481da0db5257d47778a6e6  tensorflow_io-0.24.0-cp39-cp39-win_amd64.whl
9c00f9a9880477b1dff0c71ee6734421ce99ac484ca2151793ebf2681fc0cb4c  tensorflow_io_gcs_filesystem-0.24.0-cp310-cp310-macosx_10_14_x86_64.whl
b6ca3a9f751aa9c2f9851520e666d905ad14667281bbafeabe611b7b8f3e1bc5  tensorflow_io_gcs_filesystem-0.24.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
2f67d19a2f2579dc55f1590faf48c2e882cabb860992b5a9c7edb0ed8b3eb187  tensorflow_io_gcs_filesystem-0.24.0-cp310-cp310-win_amd64.whl
cde835e68b2b43ddade07c999e7c3251bcd62b1ff165c34fbe9fc6e0f12c3ac9  tensorflow_io_gcs_filesystem-0.24.0-cp37-cp37m-macosx_10_14_x86_64.whl
71c00638c9b6048480095f2738dfefd8f4b2e7b534190c91d699aee769bfa86e  tensorflow_io_gcs_filesystem-0.24.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
d1eb5e9be62040c5a249ae8adaae7e61f65b59541139e4d6767157f25a224bf5  tensorflow_io_gcs_filesystem-0.24.0-cp37-cp37m-win_amd64.whl
cc093f160f79526d31f6070a3ddc000868d737a36ccf40984128661563383601  tensorflow_io_gcs_filesystem-0.24.0-cp38-cp38-macosx_10_14_x86_64.whl
6e65009770a05a3b55c5f782348f785e5034d277a727832811ad737bd857c8c9  tensorflow_io_gcs_filesystem-0.24.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
aa90b9a34ea8da4dbd534f77746d67375714db869524da889193c3042352679a  tensorflow_io_gcs_filesystem-0.24.0-cp38-cp38-win_amd64.whl
825f396388748038ad38c35b091311982081f93a5db8ca9763fc874c3f555e6c  tensorflow_io_gcs_filesystem-0.24.0-cp39-cp39-macosx_10_14_x86_64.whl
cbc71b3925508bf796644a0083a6f9284f71404654f53092bece701383a69520  tensorflow_io_gcs_filesystem-0.24.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
2862e0869453ce1f872a28d1362768ee078ec227ea587dd69164081dea6d7177  tensorflow_io_gcs_filesystem-0.24.0-cp39-cp39-win_amd64.whl
```

**Comment by yongtang** [comment]
Release 0.24.0 available:

https://pypi.org/project/tensorflow-io-gcs-filesystem/0.24.0/
https://pypi.org/project/tensorflow-io/0.24.0/

https://github.com/tensorflow/io/releases/tag/v0.24.0

**Comment by yongtang** [comment]
Thanks @terrytangyuan  @kvignesh1420 for the support!

I am also thinking about maybe automate the release process a little bit with GitHub Actions further, so in the future anyone within the team can ship a release when needed. Will see if I can have something in place in the next few days.

**Comment by terrytangyuan** [comment]
No problem. Yeah automated release process would be ideal.

**Comment by kvignesh1420** [comment]
That would be great! However, I remember discussing issues related to versioning in PyPI if any errors occur during the automated release. We can add a sanity check of releasing on pypi test as a starting step maybe?

**Comment by terrytangyuan** [comment]
We can continue discussing this in https://github.com/tensorflow/io/issues/1004.

**Comment by yongtang** [comment]
@kvignesh1420 @terrytangyuan The issue with PyPI is that you can only push PyPI.org once with the same version.

If we go directly to tag and release and push to PyPI, then during the build process if something is wrong, we may have to delete the published release, update the master branch, then re-tag and release again (and user may see different commit id associated with the tag). And if we already pushed to PyPI it will be much worse. It will be a little nervous to see this happen.

Recently I realized that we can have a "draft" release and modify as many times as possible. We can utilize the "draft" release in GitHub to save all the information (and even attach the pypi package into the release). When we are ready and everything is fully tested, then it is just a matter of "publish" the draft to make it visible. I think we can get the process automated without worrying about re-tag a different commit id with the same version number.

**Pull request merged**
