### PR TITLE
Reveting BigTable connector to use batch-bigtable.googleapis.com

### PR DESCRIPTION
**Pull request by vlasenkoalexey**
Most probably right fix would be to upgrade gRPC library from 1.19 to 1.21, unfortunately that breaks build and requires more work. Will look into that later.

### CODE REVIEW

**Comment by yongtang** [comment]
@vlasenkoalexey I noticed that the following changes are not in place:
```
                       .set_connection_pool_size(connection_pool_size_)
                         .set_data_endpoint("batch-bigtable.googleapis.com");
```
as there are two commits cancels each other. Just wondering if this is intended?

**Comment by vlasenkoalexey** [comment]
Yes, I'm reverting one of the changes. I got a pushback from BigTable team, they insist that connector should use batch API. As far as I understand I need to update gRPC and all related libraries in order for this to work. Will take a look at this today.

**Comment by yongtang** [comment]
@vlasenkoalexey Thanks. I will merge this PR for now. Let me know if there are anything I can be of help.

**Comment by vlasenkoalexey** [comment]
I see that gRPC version was bumped in google-cloud-cpp recently, but no new stable release was cut out yet: https://github.com/googleapis/google-cloud-cpp/commit/ec767162045961e59504978abdea8629e9299b2f#diff-c7f0cf822a57656a47eca9b634455b0d

Need to wait for release to happen before I update gRPC,  google-cloud-cpp and related libraries in IO.
@sshrdp FYI

**Pull request merged**
