### PR TITLE
Update to 0.23.1 to prepare a release

### PR DESCRIPTION
**Pull request by yongtang**
Since we removed IgniteDataset which is a major change after
0.23.0, technically it qualifies another minor release instead
of a 0.23.1 patch release. (And we need a fix for TF 2.8, see #1591).

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by kvignesh1420 — COMMENTED** [review]
@yongtang since the minor release is quite immediate, people might not have planned for the ignite deprecation (just in case if someone is using it). Shall we restore ignite and just release a patch version instead? We can remove ignite later. WDYT?

**Comment by yongtang** [comment]
@kvignesh1420 The PR has been updated. Also please see #1594 for revert of ignite removal.

**Comment by kvignesh1420** [comment]
@yongtang #1594 has been merged, can you please update the version from 0.24.0 to 0.23.1 in the PR. Thank you so much.

**Comment by yongtang** [comment]
@kvignesh1420  PR has been updated. Please take a look.

**Review by kvignesh1420 — APPROVED** [review]
LGTM. Thanks @yongtang

**Comment by yongtang** [comment]
Binary candidates:
```
$ sha256sum *.whl
e17a9426805d9c4d80c8330eea8396e5755aba260eb166443e06b3b0e6d6ade5  tensorflow_io-0.23.1-cp310-cp310-macosx_10_14_x86_64.whl
b1839a6792e23a2ae870386096c55d55f417cdcf97ee89f2149fca0483f174e2  tensorflow_io-0.23.1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
03e5232415afabe97932f2af30b7b134ce7ca2ffe73872d35da511934ba7ca25  tensorflow_io-0.23.1-cp310-cp310-win_amd64.whl
a150b62b76d444a5d8df8432e8fa47d50d0c935dd5ce754c8a304c18d7466343  tensorflow_io-0.23.1-cp37-cp37m-macosx_10_14_x86_64.whl
e3aaff1881708b643f77477895f0c99a9c251d26f8d03f1c2b5043540a0a99ec  tensorflow_io-0.23.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
72e95f8642f86b8ff4f5c30fade1ba11115fde7cd7b3351a9714b608d65b2bc0  tensorflow_io-0.23.1-cp37-cp37m-win_amd64.whl
0bc41606517269ffa152eee514c21c45e0ca7be568f039d145d7cf31f14e3a0f  tensorflow_io-0.23.1-cp38-cp38-macosx_10_14_x86_64.whl
840a8d08f78c97779782a3ad80576db87a8d5101ba0325eee0920d01b2109aa8  tensorflow_io-0.23.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
fd204d834d7260b8d8be84be238e3723ad91d6be0a1215aeca981b1d5f36a8b3  tensorflow_io-0.23.1-cp38-cp38-win_amd64.whl
06657e6d008a2f5ae612626081ba1a0252c6e48922975a55dc6447092731cb2c  tensorflow_io-0.23.1-cp39-cp39-macosx_10_14_x86_64.whl
07f1a96e940bbb3ff841dd8305e4f8784dfab3cb9b3efade5d588d9647c61eaf  tensorflow_io-0.23.1-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
0c7e3814aa3d287ebc4b0e5ea852a21af2f5e867e239636c29ab979eb5b7ba31  tensorflow_io-0.23.1-cp39-cp39-win_amd64.whl
80e2078b94ba5f140b5d366ee3b07b493760d2c76d7426ec417f7be2795a0799  tensorflow_io_gcs_filesystem-0.23.1-cp310-cp310-macosx_10_14_x86_64.whl
378b2219fd9a26ad4e92f70192cdb7cc5e12d07b206c2fd9937e92e5c876003a  tensorflow_io_gcs_filesystem-0.23.1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
5e3f87cb4d1d744ca7d474f801fadd2679f5b1b5b4ba2dccc2beba8a853fbec6  tensorflow_io_gcs_filesystem-0.23.1-cp310-cp310-win_amd64.whl
f3262a24bcc15ee7febc2c85b699e98c44dffaa4d03113dfd56d29472d07879b  tensorflow_io_gcs_filesystem-0.23.1-cp37-cp37m-macosx_10_14_x86_64.whl
650cb4ca2637345f3b75e4252f1db2f64f4fd4d15f1359ab76b9e34ad39e92fd  tensorflow_io_gcs_filesystem-0.23.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
5dea85fa7814cac81f46bc9c2f635d25e01c7657129770ee720562a2f54fb1c0  tensorflow_io_gcs_filesystem-0.23.1-cp37-cp37m-win_amd64.whl
deeedd36b7779445e6806f3c13302de4acc3a26b42e0c0a2464e38b1f722d71a  tensorflow_io_gcs_filesystem-0.23.1-cp38-cp38-macosx_10_14_x86_64.whl
4f04896024205b3c945249c1ad7a3d1681155a09107ad5a67f88724dc6a1a57d  tensorflow_io_gcs_filesystem-0.23.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
daa8d999e397b2ca9167074cdfaaf0c0226b5a66b7788b4153a62f597028e44d  tensorflow_io_gcs_filesystem-0.23.1-cp38-cp38-win_amd64.whl
fe0f375a1806f99ad9f0315d157732cb073105b9022c1fd6f39b7e0cbf43e927  tensorflow_io_gcs_filesystem-0.23.1-cp39-cp39-macosx_10_14_x86_64.whl
7940b90faf633e4bb27dd1579a7a55dfb56921c879c867c732a0c0c96f29542b  tensorflow_io_gcs_filesystem-0.23.1-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
15d9a8e86355fcc1fc6fd06a8ee2fcb89431dafbb9e3560dfd9a35443b22c6fc  tensorflow_io_gcs_filesystem-0.23.1-cp39-cp39-win_amd64.whl
```

**Comment by yongtang** [comment]
Release of 0.23.1:

https://pypi.org/project/tensorflow-io/0.23.1/
https://pypi.org/project/tensorflow-io-gcs-filesystem/0.23.1/

https://github.com/tensorflow/io/releases/tag/v0.23.1

**Pull request merged**
