### PR TITLE
[WIP] Update bazel to 0.26.1, and update google cpp to v0.9.0

### LINKED ISSUE #248: Build with bazel 0.25.3 fails
While trying to build with bazel 0.25.3, the following error encountered:
```
ERROR: /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/ \
external/com_github_googlecloudplatform_google_cloud_cpp/google/cloud/BUILD \
:31:11: in cmd attribute of genrule rule \
@com_github_googlecloudplatform_google_cloud_cpp//google/cloud:generate_build_info: \
$(CC) not defined
```

Believe this issue is related to https://github.com/bazelbuild/bazel/issues/6867

Might need to update github.com/googleapis/google-cloud-cpp to v0.9.0, and some other fixes.

### PR DESCRIPTION
**Pull request by yongtang**
This fix fixes #248

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
Update, looks like Bazel 0.26.1 may have bugs in macOS.

**Comment by damienpontifex** [comment]
@yongtang I've been using bazel 0.27 on macOS without any current issues. Worth skipping straight to that if you're seeing issues here?

**Comment by yongtang** [comment]
Thanks @damienpontifex. I just tried bazel 0.27.0 and see it fails on Ubuntu 14.04:
```
# bazel build -s --verbose_failures //tensorflow_io/core:all
/usr/local/bin/bazel: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/bin/bazel)
/usr/local/bin/bazel: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/local/bin/bazel)
/usr/local/bin/bazel: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/bin/bazel)
```

Related: https://github.com/bazelbuild/bazel/issues/8652

Give TensorFlow binaries are still built on Ubuntu 14.04 (and not truly compatible with Ubuntu 16.04+), we may have to wait until this is fixed. I think even TensorFlow main repo will be impacted.

**Comment by damienpontifex** [comment]
@yongtang I noticed that linked issue is now closed. Any success on bazel 0.27.1 ?

**Comment by yongtang** [comment]
@damienpontifex with Bazel 0.27.1 the following error surfaced:
```
ERROR: /v/tensorflow_io/grpc/BUILD:31:1: in _generate_cc rule //tensorflow_io/grpc:_endpoint_cc_grpc_codegen: 
Traceback (most recent call last):
	File "/v/tensorflow_io/grpc/BUILD", line 31
		_generate_cc(name = '_endpoint_cc_grpc_codegen')
	File "/root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/external/com_github_grpc_grpc/bazel/generate_cc.bzl", line 44, in generate_cc_impl
		[f for src in ctx.attr.srcs for f in src.proto.check_deps_sources]
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
ERROR: Analysis of target '//tensorflow_io/grpc:_endpoint_cc_grpc_codegen' failed; build aborted: Analysis of target '//tensorflow_io/grpc:_endpoint_cc_grpc_codegen' failed; build aborted
```

This error likely has been fixed in (https://github.com/grpc/grpc/commit/49f0fb9035120d0f5b5fa49846324c0b2d59c257) though it is not in the release of grpc yet.

**Comment by yongtang** [comment]
With PR #465 merged, now we are in bazel 0.29.0 with googleapi/grpc all updated to the latest. This PR could be closed.

**Pull request closed without merging**
