### PR TITLE
Add ImageInputSequence class for metadata information with a list of images

### PR DESCRIPTION
**Pull request by yongtang**
This PR adds an ImageInputSequence class so that metadata information
of a list of images (one image could have multiple frames) is stored
as a resource. The meta data information could later be
obtained without re-compute (as the information are static).

At the moment two methods are added: `count()` which returns
the number of frames, and `type()` which returns the fourcc
file type of each frame.

Additional meta data information could be added later.

This PR is inspired by #109.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by suphoff** [comment]
@yongtang: I hope I can convince you to use Variants instead of Resources.
In my opinion Variants are a lot more versatile as they can be stored as tensors and passed around in a compute graph - just like any other values. One example operation I had in mind would take a vector (batch) of Imagesource variants and decode (potentially cropped, scaled) images with equal size directly into a batched output tensor.
In general I have the feeling that passing references around (via Variants) will allow future optimizations using lazy evaluation, All the benefits of Resources (persistence across runs) can easily be archived by storing variants tensors in TF variables - additionally allowing multiple variants to be stored in a persistent table.

I just pushed some utility code to make it easy to wrap objects in Variants to https://github.com/suphoff/io/tree/imagesource - it only contains the framework and no actual image related code as I got stuck last week looking at the vastly different capabilities of the standard low level image libraries. ( jpeg - discrete scaling only, webp - cropping only on even values for some encodeing, ..)
However I hope that you find it useful as it allows for easy separation of Image related code to common boiler plate code required to wrap objects into Variants.

**Comment by yongtang** [comment]
@suphoff The variant type really makes sense for image operations. Though the resource approach I implemented, is actually focusing on a different problem about file compression/archive/containers.

As we adds more support for file formats and provides user a better experience, we want to automatically process compression, archiving, and containers. For example, when user specify a zip file, we should just atomically decompress the zip into a collection of files, and treat one zip file as a set of files. Zip file could be big and many contents might not be needed (e.g., user may only want to process jpeg files in zip and ignore and blob file or txt files).

Zip is a standard format for archive but there are other "container" types of files. One example is the video file. We could treat one video file as a standalone blob and decode, or we could treat one video file as a "container/archive" with many images. Decoding everything in a big video file (could be GBs), or even just copy this GBs of data into memory, is really unnecessary, and hard to manage in a graph. I think it fits naturally with resource as we could avoid passing GB's of protobuf-encoded message in graph around.

After looking into your idea, I think we could do it in this way:
- A resource that handles archives, directories, or containers (e.g., mp4) as a sequence of objects.
- The resource will expose an `getitem` types of API so that it is possible to extract one or multiple objects of interests. The returned value will be variant.
- At another level, we will process the variant (object), decode/crop the image or frame, or get the image meta data information like height, width, channel, exactly as you have been doing.

I think that will be a good plan to maintain separation of objects (variant) and the higher level processing (e.g., crop/bbox/etc).

**Comment by yongtang** [comment]
@suphoff I will close this PR, and open another PR to keep the resource management with focus on archives, compressions, and containers. Will you be able to open a PR to focus on the image processing part? I think a PR (even if WIP) would be great.

**Comment by suphoff** [comment]
@yongtang : I will try to push out a WIP this week.

I had never looked at the zip format internals before  - have you considered implementing a stacked zip filesystem on top of the tensorflow filesystem?

**Pull request closed without merging**
