### PR TITLE
Add GCS configuration ops.

### PR DESCRIPTION
**Pull request by rjpower**
These operations allow users to adjust the default block cache behavior and transmit GCS authentication cookies to a running TF server.

### CODE REVIEW

**Comment by rjpower** [comment]
@henrytansetiawan the GCS configuration ops are partly based on your bigquery CL.

**Comment by yongtang** [comment]
@rjpower Thanks for the PR! Can you fix the pylint errors (you could see from the end of the Travis CI Lint run):
https://travis-ci.org/tensorflow/io/jobs/556992547

**Comment by rjpower** [comment]
Thanks for the quick review. Last failure on the Python2/3 builds looks unrelated to this change, but please let me know if there's anything I should change!

**Comment by yongtang** [comment]
@rjpower Some small fixes are still needed to pass all tests. See  3d90418

Since v0.7.0 will be released shortly, I will just merge this PR and carry the fix through another PR.

**Pull request merged**
