### PR TITLE
Authenticate with device code to azure

### PR DESCRIPTION
**Pull request by damienpontifex**
Unsure on whether this is the best place for this, but it eases retrieval of authentication information for azure storage access.

Idea being you could call `authenticate_with_device_code` inside your interactive code to automatically set up auth information for az:// storage use. 

Another investigation is how to use azure CLI auth to retrieve this information if a user is already logged in on their machine

### CODE REVIEW

**Comment by yongtang** [comment]
Thanks @damienpontifex, can you take a look at lint issue?
```
************* Module tensorflow_io.azure
W: 83,27: map/filter on lambda could be replaced by comprehension (deprecated-lambda)
```

**Comment by damienpontifex** [comment]
@yongtang seems like test failures from Travis. I can't see any connection to this change though

**Comment by yongtang** [comment]
@damienpontifex Can you try to rebase with the master? There might be some changes recently that may has some side effects.

**Comment by yongtang** [comment]
@damienpontifex All tests passed now.

**Pull request merged**
