### PR TITLE
Issue #552: Add naming conventions and prefixes in docs for development guide

### PR DESCRIPTION
**Pull request by ricky3dec**
1. Add naming convention guidelines to README.md
2. Add the SIG IO logo to README.md :-)

### CODE REVIEW

**Comment by ricky3dec** [comment]
Hello @yongtang, here is an initial effort to document the naming conventions to be followed. Please review it.

Referring to Tensorflow & Tensorflow Addons projects, I think eventually these guidelines and other development inputs would become part of CONTRIBUTING.md, and should be removed from README.md as such?

**Comment by yongtang** [comment]
@ricky3dec Thanks for the PR! We could move contributing to docs page. 

I think essentially we add a contributing.md in docs/ directory, and then add a:
```
- title: Overview
   path: /addons/overview
```

In a way similar to Addons:
https://github.com/tensorflow/addons/pull/583/files

**Comment by yongtang** [comment]
@ricky3dec I will merge this PR for now. Would you like have follow up PR to move the related content to contributing.md?

**Comment by ricky3dec** [comment]
Sure @yongtang , I can work on that!

**Pull request merged**
