### PR TITLE
Install gs plugin for api and benchmarking checks

### PR DESCRIPTION
**Pull request by kvignesh1420**
This PR handles the failures in API compatibility checks and benchmarking jobs due to the dependency on the new `tensorflow-io-plugin-gs`.

### CODE REVIEW

**Comment by yongtang** [comment]
@kvignesh1420 I think `tensorflow-io-nightly` depends on `tensorflow-io-plugin-gs-nightly` so it will be installed directly. Though the gs plugin will not be invoked through `import tensorflow_io`, instead it will only be invoked through `import tensorflow_io_plugin_gs` (to allow tensorflow integration in later versions).

**Comment by kvignesh1420** [comment]
@yongtang if that's the case, this PR can be closed. However for an unknown reason, the compatibility tests are failing for `https` fs plugin. The tests pass locally though.

**Comment by yongtang** [comment]
@kvignesh1420 I will take a look.

**Comment by yongtang** [comment]
@kvignesh1420 I see where the issue is: while `tensorflow-io-nightly` correctly depends on `tensorflow-io-plugin-gs-nightly`, the api and benchmark test actually uses `python -m pip install --no-deps -U` to install, which does not install dependency due to `--no-deps` (because it needs to adjust the tensorflow's dependency version). Because of that, the `tensorflow-io-plugin-gs-nightly` is not getting installed. I think we still need to install `tensorflow-io-plugin-gs-nightly` manually with the same version as `tensorflow-io-nightly`. Sorry for the back and forth.

**Comment by kvignesh1420** [comment]
@yongtang no problem. I have re-opened the PR. PTAL.

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
