### PR TITLE
Add @com_google_absl//absl/strings:cord

### PR DESCRIPTION
**Pull request by yongtang**
While trying to build tensorflow-io against tf-nightly (not tensorflow package), I noticed there were some additional fixes that will be needed to compile.

Since they are additional includes and will not impact existing build, and we will update to next version of tensorflow soon, it makes sense to have the update.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by kvignesh1420 — COMMENTED** [review]
@yongtang can you please provide any references regarding this change?

**Comment by yongtang** [comment]
@kvignesh1420 I am testing this change locally by:
```
./python3 -m pip install -U tf-nightly
./configure.sh
```

which overrides the default install of `tensorflow>=2.4.0`.

After that, run bazel like before (now headers are pointing to tf-nightly):
```
bazel build -s --verbose_failures //tensorflow_io/...
```

Without the PR change, the build will fail in several places. The build failure is likely caused by tensorflow's master branch change recently (showed up in tf-nightly).

**Comment by kvignesh1420** [comment]
@yongtang I think we should add the tfio build verification step to `API-Compatibility` Github-Actions workflows as well. We can thus identify these kinds of issues without human intervention. What do you think?

**Comment by yongtang** [comment]
@kvignesh1420 Yes I think we can add an additional test to test against daily tf-nightly so that any build failures could be detected. The test can run everyday.

**Review by kvignesh1420 — APPROVED** [review]
thanks for the info @yongtang.

**Pull request merged**
