### PR TITLE
Bump abseil-cpp to 6f9d96a1f41439ac172ee2ef7ccd8edf0e5d068c

### PR DESCRIPTION
**Pull request by yongtang**
This PR bumps abseil-cpp to 6f9d96a1f41439ac172ee2ef7ccd8edf0e5d068c
to fix the build issue.

See related changes in  tensorflow/tensorflow@1c9eeb9

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by oliverhu** [comment]
thanks for fixing the build!

**Review by kvignesh1420 — CHANGES_REQUESTED** [review]
@yongtang this is unrelated to this CL but seems like the flaky centos7 action has been restored due to an improper rebase in https://github.com/tensorflow/io/pull/1283. Can you please remove that task as well in this PR?
https://github.com/tensorflow/io/blob/e4bde0eded6adf7aa1fc9ae3d4d7dcff0baec806/.github/workflows/build.yml#L91-L105

**Comment by yongtang** [comment]
Thanks @kvignesh1420 . PR has been updated. Please take a look

**Review by kvignesh1420 — APPROVED** [review]
Thanks @yongtang

**Pull request merged**
