### PR TITLE
Update Apache Arrow to 0.11.1

### PR DESCRIPTION
**Pull request by yongtang**
This fix updates Apache Arrow to 0.11.1. Since Parquet is part of the Apache Arrow now, the Parquet library has been removed.

The Parquet headers are still generated like before, except it is included as part of the `arrow/cpp/src/parquet`.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
@BryanCutler It looks like the Parquet Cpp library is now part of the Arrow library. I update the arrow dependency (with parquet related cpp files added) and removed the parquet dependency in the PR. Please take a look.

**Comment by BryanCutler** [comment]
Thanks for doing this! For #36 I also needed a number of source files in `arrow/ipc` and `arrow/io` as well as the Flatbuffers library, which I added [here](https://github.com/tensorflow/io/pull/36/files#diff-3d9afc4dcae8956fef470785cc5cf75aR12).  Would you like me to make a PR to add them here or just update my branch once this is merged?

**Comment by yongtang** [comment]
Thanks @BryanCutler. I think we could merge this PR now, then additional needed source files (in arrow.BUILD) could be added from your arrow PR there. Let me merge this PR.

**Comment by BryanCutler** [comment]
> Thanks @BryanCutler. I think we could merge this PR now, then additional needed source files (in arrow.BUILD) could be added from your arrow PR there. Let me merge this PR.

Sounds good to me, thanks!

**Pull request merged**
