### PR TITLE
Adding memcached_file_block_cache to gstpufs

### PR DESCRIPTION
**Pull request by marioecd**
Adding memcached_file_block_cache to gstpufs

### CODE REVIEW

**Comment by yongtang** [comment]
@marioecd Maybe you can hold on a little bit. I think I get libmemcached compiled on macOS with some modifications. Currently testing. Once done that can help avoid adding extra `select` in BUILD files.

**Comment by marioecd** [comment]
Ok, I will stand by. Thanks!

**Comment by marioecd** [comment]
Btw, possibly the latest rebase may have brought a build failure. 

bazel build -s --verbose_failures //tensorflow_io/...
ERROR: /home/marioecd/io/tensorflow_io/core/BUILD:173:1: no such package '@libavif//': The repository '@libavif' could not be resolved and referenced by '//tensorflow_io/core:image_ops'
ERROR: Analysis of target '//tensorflow_io/bigquery:bigquery' failed; build aborted: no such package '@libavif//': The repository '@libavif' could not be resolved
INFO: Elapsed time: 0.353s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (36 packages loaded, 322 targets configured)
    currently loading: @com_github_grpc_grpc//src/compiler ... (2 packages)

**Comment by yongtang** [comment]
@marioecd The `nightly` branch has been pushed. You can try to rebase and see if it works.

Also, I noticed sometimes you do a merge (assume `git merge ..`?). As git itself's is non linear DAG, a merge may have unintended effect if the DAG is not straightforward. In some situations `git rebase ` might be a good choice as rebase carries change on top of the latest head. This can avoid overlapping changes when DAG is not clear.

**Comment by marioecd** [comment]
I will try to use rebase.

Were you able to test the libmemcached compiling on macOS? Did it work?

**Comment by yongtang** [comment]
@marioecd Yes it works on macOS and Linux:

https://github.com/tensorflow/io/actions/runs/110928651

(I skipped Windows for now. Though I suspect it might be possible to port it as well. I may give Windows a try later).

**Comment by marioecd** [comment]
Great to hear! Thanks! I will test this locally a bit and prepare a new PR.

**Pull request closed without merging**
