### PR TITLE
Update abseil-cpp to align with TF 2.5.0rc2

### PR DESCRIPTION
**Pull request by yongtang**
See tensorflow 404f96bfa for details

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by vnvo2409** [comment]
Thank you !

**Review by kvignesh1420 — APPROVED** [review]

**Comment by kvignesh1420** [comment]
This somehow fixes the failures in
```
GitHub CI / macOS (pull_request) 
GitHub CI / Linux (pull_request) 
```
based on current master.

**Review by terrytangyuan — APPROVED** [review]

**Comment by vnvo2409** [comment]
FWIW, It seem that `absl` is reverted in `TF 2.5rc3` https://github.com/tensorflow/tensorflow/commit/844ba87f6d584bd3c3342cf25a1059403ccfb5ce.

**Review by terrytangyuan — APPROVED** [review]

**Comment by yongtang** [comment]
Looks like the windows build failure is for real. On the other hand, absl is reverted in TF 2.5rc3... Maybe we can pin the version to TF 2.5rc1 for now, and bump to 2.5rc3 directly once it is out.

**Comment by kvignesh1420** [comment]
@yongtang SGTM.

**Comment by yongtang** [comment]
Closed as this is replaced in #1386

**Pull request closed without merging**
