### PR TITLE
Update _toc.yaml to reflect avro tutorial

### PR DESCRIPTION
**Pull request by burgerkingeater**

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]

**Review by kvignesh1420 — APPROVED** [review]

**Comment by burgerkingeater** [comment]
i wonder how we can make the avro tutorial appear in https://www.tensorflow.org/io/overview? @kvignesh1420

**Comment by kvignesh1420** [comment]
The TensorFlow docs team has to push the latest docs so that it reflects in the site.
cc: @MarkDaoust @lamberta to check and push the docs.

**Comment by burgerkingeater** [comment]
@MarkDaoust @lamberta can we push the docs? Thanks.

**Comment by MarkDaoust** [comment]
Let's see if we can merge: https://github.com/tensorflow/io/pull/1274

**Comment by MarkDaoust** [comment]
This one is done. 

https://www.tensorflow.org/io/tutorials/avro

**Comment by yongtang** [comment]
Thanks @MarkDaoust 👍 🎉 !

**Pull request merged**
