### PR TITLE
Support for HDF5 Files: Work in Progress

### PR DESCRIPTION
**Pull request by captain-pool**
cc: @yongtang

### CODE REVIEW

**Comment by yongtang** [comment]
There are some work need to be done. We could start with lint and python API first.

**Comment by yongtang** [comment]
For lint:
  If you have docker installed, can you run the following command:
```
docker run -i -t --rm -v $PWD:/v -w /v --net=host golang:1.12 bash -x -e -c 'go get github.com/bazelbuild/buildtools/buildifier && buildifier $(find . -type f \( -name WORKSPACE -or -name BUILD -or -name *.BUILD \))'
```

**Comment by yongtang** [comment]
The dataset field effectively are column labels which could be similar to parquet or csv with df concept. A new field selection will be needed to make it work. You can try hard code one to make the program build.

I will update the API shortly to make the selection of data fields available.

**Comment by yongtang** [comment]
@captain-pool PR #219 has been merged. It adds the columns field which will allow you to specify the dataset for output in hdf5.

**Comment by captain-pool** [comment]
> @captain-pool PR #219 has been merged. It adds the columns field which will allow you to specify the dataset for output in hdf5.

Hey @yongtang  Thanks for the Update. Can you give me some example related to it?

**Comment by captain-pool** [comment]
Also @yongtang, There's no vector for output tensor. How am I supposed to return the result?
https://github.com/tensorflow/io/blob/189e2414ee87f23a4ac1b2f9a0b9dd5c22f50d54/tensorflow_io/core/kernels/dataset_ops.h#L254

**Comment by captain-pool** [comment]
> > @captain-pool PR #219 has been merged. It adds the columns field which will allow you to specify the dataset for output in hdf5.
> 
> Hey @yongtang Thanks for the Update. Can you give me some example related to it?

Nevermind!
Thanks for adding the support!

**Comment by yongtang** [comment]
@captain-pool I think you can rebase against the master to have the `ReadRecord` in, then add additional tests in `tests/test_hdf5.py`.

**Comment by yongtang** [comment]
@captain-pool It seems this PR is stalled. I will close the PR for now, but please reopen if merge conflicts have been resolved, and thanks for your contribution.

**Pull request closed without merging**
