### PR TITLE
Feature/griffin lim

### PR DESCRIPTION
**Pull request by douglas125**
This PR changes audio_ops to include audio reconstruction function `inverse_spectrogram` using Griffin-Lim algorithm.
It addresses issue https://github.com/tensorflow/io/issues/1585

What was changed:

- Added `tfio.audio.inverse_spectrogram`
- Added tests to check if the reconstructed audio statistics match the original

### CODE REVIEW

**Comment by douglas125** [comment]
@yongtang I think you need to approve the workflow? I submitted the CLA

**Comment by kvignesh1420** [comment]
@douglas125 I approved the workflow run for now, but I still see a CLA failure.

**Comment by douglas125** [comment]
That's weird - I click to open the page and see

```
Google Individual Contributor License Agreement
Below is the contact information we have for your Google Individual CLA. The information you provide below, along with your IP address and a timestamp, will be maintained in accordance with Google's privacy policy.

It looks like you've already signed this CLA. If you'd like to edit your contact information, you may do so below.

* required fields
```

I am checking the other fails

**Comment by kvignesh1420** [comment]
I think a new commit after signing the CLA was needed for the check to pass.

**Comment by douglas125** [comment]
@kvignesh1420 an unrelated test is failing intermittently in macOS. Any suggestions?

Should I include some form of documentation and samples in this PR or can it be at a later time?

This is somewhat simple but I think it would be useful to drop an example where appropriate.

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by yongtang** [comment]
I think documentation can be added as a follow up PR into io/docs/tutorials/audio.ipynb

**Comment by douglas125** [comment]
I thought I'd leave some sample audio / inverse stft reconstruction pairs with a few different configs so people browsing Issues can have a better idea about what this `inverse_spectrogram` is about and what the reconstruction sounds like.
In principle, I'm going to add those to https://github.com/tensorflow/io/issues/1585 .

**Comment by kvignesh1420** [comment]
> @kvignesh1420 an unrelated test is failing intermittently in macOS. Any suggestions?
> 
> Should I include some form of documentation and samples in this PR or can it be at a later time?
> 
> This is somewhat simple but I think it would be useful to drop an example where appropriate.

@douglas125 It was an unrelated test failure. I have triggered the jobs again.

**Review by kvignesh1420 — APPROVED** [review]
LGTM. Thanks @douglas125

**Pull request merged**
