### PR TITLE
Maybe fix npm install.

### PR DESCRIPTION
**Pull request by MarkDaoust**
For #783

The install was failing silently.

### CODE REVIEW

**Comment by MarkDaoust** [comment]
Wait, let me clear the output before merging.

**Comment by MarkDaoust** [comment]
Done.

**Comment by yongtang** [comment]
@MarkDaoust When I try the notebook on Google Colab, it give the following error:
```
!npm --user install -g azurite@2.7.0

Error: setuid user id does not exist
    at /tools/node/lib/node_modules/npm/node_modules/uid-number/uid-number.js:49:16
    at ChildProcess.exithandler (child_process.js:267:7)
    at emitTwo (events.js:126:13)
```

On the other hand, if I try with the following (remove `-g` from the original, also removes `--user`):
```
!npm install azurite@2.7.0
```
Then the install is successful. 

Don't know about your local setup, though I guess the error you encountered locally before (with `!npm install -g azurite@2.7.0`) might be due to the usage of `-g`?

Would you mind give `!npm install azurite@2.7.0` a try locally? That might clear both the local execution error and Colab error?

**Comment by MarkDaoust** [comment]
> !npm install azurite@2.7.0

Works locally, and in colab. Worth a shot. let's merge and see if that fixes the publisher.

**Pull request merged**
