### PR TITLE
Revert "switch to `Aws::S3::Model::ListObjectsV2Request` (#1384)"

### PR DESCRIPTION
**Pull request by yongtang**
We have been seeing CI failures where segmentation faults are being thrown out randomly. Several attempts have been made to resolve the issue though as the seg fault does not happen all the time, it has been hard to track down to which commit was the issue.

I have been trying to bisect the past commits, and run GitHub Actions multiple times for the past couple of days on my repo. (See branch build with name `fix`|`fix2`...`fix6`|`fix8`):
https://github.com/yongtang/io/actions

The issue points to d08b554f1d4ab5cebd93829b5431383670774c75 (or in combination of 63259e7b5ee7e3f935a7ad6852e7ab8897271821).

Not exactly sure why this is causing the issue. Though I think we want to revert the commit first as TF 2.5.0 (and our tensorflow-io 0.18.0 release is imminent).

In order to avoid false negative, I will trigger CI build multiple times to make sure this is the true fix.

This PR reverts the commit.
/cc @vnvo2409 FYI

This reverts commit d08b554f1d4ab5cebd93829b5431383670774c75.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
The issue seems to be harder than thought. It looks like up before d08b554 segmentation fault didn't happen. However, merely revert d08b554 does not necessarily resolve all problems (there is still 142 exit code which is another issue).

**Comment by vnvo2409** [comment]
@yongtang Thank you !

I'm also examining the segfault. From the CI log, I find that the segfault usually falls on `test_io_tensor`.
- [`test_io_tensor.py::test_io_tensor_slice[audio[wav|s24]]`](https://github.com/tensorflow/io/runs/2533514703?check_suite_focus=true)
- [`test_io_tensor.py::test_io_tensor_slice[audio[wav]]`](https://github.com/tensorflow/io/runs/2533773807?check_suite_focus=true)
- [`test_io_tensor.py::test_io_tensor_slice[audio[wav|s24]]`](https://github.com/tensorflow/io/runs/2534106385?check_suite_focus=true)
- [`test_io_tensor.py::test_io_tensor_slice[audio[wav|s24]]`](https://github.com/tensorflow/io/runs/2534856608?check_suite_focus=true)

Some other tests:
- [`test_filesystem.py::test_gfile_glob[az-None]`](https://github.com/tensorflow/io/runs/2536064332?check_suite_focus=true)
- [`test_ffmpeg.py::test_video_predict`](https://github.com/tensorflow/io/runs/2528805538?check_suite_focus=true)
- [`test_text.py::test_text_output_sequence`](https://github.com/tensorflow/io/runs/2514596907?check_suite_focus=true)

---

While I am playing with `google-cloud-cpp` for pubsub integration, I got an error:
```
Application Specific Information:
abort() called
Python(2247,0x70000578c000) malloc: *** error for object 0x7fb2444dd0c8: pointer being freed was not allocated
 

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff205c68e2 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff205f8e6f _pthread_cond_wait + 1254
2   libc++.1.dylib                	0x00007fff2055fcf2 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   _pywrap_tensorflow_internal.so	0x00000001288f12db nsync::nsync_mu_semaphore_p_with_deadline(nsync::nsync_semaphore_s_*, timespec) + 315
4   _pywrap_tensorflow_internal.so	0x00000001288edbb9 nsync::nsync_cv_wait_with_deadline_generic(nsync::nsync_cv_s_*, void*, void (*)(void*), void (*)(void*), timespec, nsync::nsync_note_s_*) + 393
5   _pywrap_tensorflow_internal.so	0x00000001288ee331 nsync::nsync_cv_wait(nsync::nsync_cv_s_*, nsync::nsync_mu_s_*) + 49
6   _pywrap_tensorflow_internal.so	0x0000000122b6b9eb tensorflow::data::ParallelMapDatasetOp::Dataset::Iterator::GetNextInternal(tensorflow::data::IteratorContext*, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*, bool*) + 699
7   libtensorflow_framework.2.dylib	0x000000013c43d349 tensorflow::data::DatasetBaseIterator::GetNext(tensorflow::data::IteratorContext*, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*, bool*) + 185
8   _pywrap_tensorflow_internal.so	0x00000001231708bf tensorflow::data::experimental::MaxIntraOpParallelismDatasetOp::Dataset::Iterator::GetNextInternal(tensorflow::data::IteratorContext*, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*, bool*) + 703
9   libtensorflow_framework.2.dylib	0x000000013c43d349 tensorflow::data::DatasetBaseIterator::GetNext(tensorflow::data::IteratorContext*, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*, bool*) + 185
10  _pywrap_tensorflow_internal.so	0x0000000123098bef tensorflow::data::ModelDatasetOp::Dataset::Iterator::GetNextInternal(tensorflow::data::IteratorContext*, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*, bool*) + 639
```

IIRC, I've already saw the same error ( but different stacktrace in another test ) `Python(2247,0x70000578c000) malloc: *** error for object 0x7fb2444dd0c8: pointer being freed was not allocated`.

Futhermore, I ran `test_io_dataset` 10000 times locally but it passed everytime, I am suspecting it might be because we run test on the same time.

After `0.18` release, could we add some `cc_test` for `asan`, `tsan` and `usan` ?

**Comment by yongtang** [comment]
@vnvo2409 One thing I remember is that grpc used to give us quite some trouble before:
https://github.com/grpc/grpc/issues/20034

Don't know if recent set fault is caused by grpc as well? (We added/updated several libraries).

**Comment by yongtang** [comment]
> After 0.18 release, could we add some cc_test for asan, tsan and usan ?

@vnvo2409 Yes I think this can be one of the focus after 0.18.

**Comment by vnvo2409** [comment]
@yongtang Could we have a more detailed stacktrace ? I am trying to get `gdb` working on Linux. But I am not sure what to do on Mac.

**Comment by yongtang** [comment]
@vnvo2409 On macOS the console will pop up with details of the stacktrace window if crash happens. However, I haven't been able to find where the log is located on GitHub Actions yet.

PR #1410 is the effort to isolate crashes and get overall test pass/failure with xdist+multiprocess.

**Comment by yongtang** [comment]
This PR has been superseded by #1410.

**Pull request closed without merging**
