### PR TITLE
Add test for `hdfs` filesystem

### PR DESCRIPTION
**Pull request by vnvo2409**
This PR added test for `hdfs`. `har` and `viewfs` requires sepecial setup and I am still thinking how to test it

I also changed the emulator because https://github.com/sequenceiq/hadoop-docker was marked as obsoleted and https://github.com/big-data-europe/docker-hadoop infra is closer to production. Failed tests related to https://github.com/tensorflow/io/pull/1401

---

@kvignesh1420 I want to benchmark the filesystem but they are falling because of missing `gs`. Do you know why ?

### CODE REVIEW

**Comment by kvignesh1420** [comment]
will take a look

**Comment by kvignesh1420** [comment]
@yongtang as https://github.com/tensorflow/io/pull/1413 is merged, you can try benchmarking your fs tests.

**Comment by vnvo2409** [comment]
@yongtang Could you take a look at this PR ?

**Review by yongtang — APPROVED** [review]
LGTM

**Pull request merged**
