### PR TITLE
Dicom tuto

### PR DESCRIPTION
**Pull request by ZWael**
suggesting a new a new subchapter for working with dicom tags in tfio
"Decode DICOM Metadata and working with Tags "

my tuto file is named io_dicom.ipynb as suggested in "io/docs/tutorials/README.md"

### CODE REVIEW

**Comment by ZWael** [comment]
> 
> 
> @ZWael I am wondering if your change can be added to docs/tutorials/dicom.ipynb instead? As both discussed about DICOM?

Indeed Yes,  my contribution was about working with metadata and dicom tags, i was working on dicom data and the tensorflow_io tutorial for dicom was only about the pixel array data.

I named the notebook io_dicom as the io/docs/tutorials/readme file stated The notebook should be named subpackage_submodule 

best regards

Wael

**Comment by ZWael** [comment]
?

**Comment by yongtang** [comment]
@ZWael As was mentioned in https://github.com/tensorflow/io/pull/1493#issuecomment-897011651 , I am wondering if you can combine the tutorial here (docs/tutorials/io_dicom.ipynb) into the existing dicom tutorial (io/docs/tutorials/dicom.ipynb)? They are covering different areas, but user/readers will be able to read through with one tutorial. You can add your authoring information and references at the end of the existing tutorial if needed?

**Comment by ZWael** [comment]
> #1493
Hi @yongtang 
I was not able to change directly the name of the tuto file 
so i proceed with a new pull request #1502 
hope it is fine

**Pull request closed without merging**
