### PR TITLE
Adding basic gstpu file system.

### PR DESCRIPTION
**Pull request by marioecd**
I will gradually add more logic here to add TPU-specific optimizations for datasets reading from the GCS file system. This file system will allow users to get tpu optimizations by simply using the gstpu:// dataset scheme instead of gs:// when TF is running on TPU.

### CODE REVIEW

**Comment by yongtang** [comment]
@marioecd The GitHub CI failures are not related to your changes. I have updated the nightly branch with additional fixes:
https://github.com/tensorflow/io/commits/nightly

If you rebase your branch and push again then GitHub CI should pass I think.

**Comment by yongtang** [comment]
@googlebot I consent.

**Comment by yongtang** [comment]
@marioecd I think you includes the commit from master branch as well. That may cause other issues as master is still waiting for TF 2.2.0 release.

Can you just rebase `nightly` branch? Let me know if you encounter any issues.

**Comment by marioecd** [comment]
Oh I see. I will try to rebase the nightly branch now. Thanks!

**Comment by marioecd** [comment]
Not sure why it shows 37 files changed and 26 commits in my PR. I am probably doing something pretty silly.

**Comment by yongtang** [comment]
@marioecd I think one way of resolving this, assume you have `origin` pointing to your fork repo `https://github.com/marioecd/io.git`, and `upstream` pointing to `https://github.com/tensorflow/io.git`:


**Note please have `nightly2` branch as backup in case something is wrong.**

1. rename your currently local `nightly` to `nightly2` branch, and remove `origin/nightly` tracking
   ```
   git checkout nightly
   git branch -m nightly
   git branch -r -d origin/nightly
   ```
2. Pull latest nightly of upstream:
   ```
   git fetch upstream nightly
   ```
3. Create a local `nightly` branch from `upstream/nightly`. Since your original `nightly` branch has been renamed as `nightly2` in 1), and `origin/nightly` tracking is removed, the checked branch should match upstream nightly with latest commit of `Skip Kafka Test (a482959)`:
   ```
   git checkout nightly
   ```
4. Cherry-pick your commits in nightly2:
   ```
   git cherry-pick 3ac15ab
   git cherry-pick 074a1e8
   git cherry-pick fe209ed
   git cherry-pick 9cba55b
   git cherry-pick 7fef653
   ```

Now the local nightly branch should only have 5 commit difference compared with `upstream/nightly`

The above is not exactly straightforward but it will give you a "clean state". If everything is fine, you can force push:
```
git push -f origin nightly
```

**Comment by marioecd** [comment]
Thanks a lot! That was very helpful.

**Comment by marioecd** [comment]
Looks like a Bazel Windows test is failing.

**Comment by yongtang** [comment]
@marioecd I think the windows build failure is caused by the fact that gcs_file_system is not included in tensorflow's tf-nightly build wheel package. Added a PR in TensorFlow Core repo https://github.com/tensorflow/tensorflow/pull/38959 for the fix.

Also, linked  https://github.com/tensorflow/tensorflow/issues/19297 FYI

**Comment by marioecd** [comment]
Thanks! So, should I wait for tomorrows tf-nightly build to get cut and then retry this check in my PR?

**Comment by yongtang** [comment]
@marioecd Will need to get https://github.com/tensorflow/tensorflow/pull/38959 merged. Then normally tf-nightly will show up next day. Then the next run of this PR will pass I think.

**Comment by marioecd** [comment]
Since the windows error is not related to my change. Would it be possible at all to submit my PR bypassing the windows check error, or does it need to block until https://github.com/tensorflow/tensorflow/pull/38959 is in? Thanks!

**Comment by yongtang** [comment]
@marioecd I think you can move line `"//tensorflow_io/gstpufs:gs_tpu_file_system",` into the ` "//conditions:default": [` parts:
```
        "@local_config_tf//:libtensorflow_framework",
        "@local_config_tf//:tf_header_lib",
    ] + select({
        "@bazel_tools//src/conditions:windows": [],
        "//conditions:default": [
            "//tensorflow_io/core:core_ops",
            "//tensorflow_io/core:genome_ops",
            "//tensorflow_io/core:optimization",
            "//tensorflow_io/core/oss:oss_ops",
            "//tensorflow_io/gcs:gcs_config_ops",
             "//tensorflow_io/gstpufs:gs_tpu_file_system",
        ],
    }),
```

That will skip the build on windows (notice `"@bazel_tools//src/conditions:windows": [],` line will selectively ignore the components on windows).

Also can you move `gstpufs` code into `tensorflow_io/core/kernels/gstpufs` directory?

The file structure is shared by python and c++ so we are trying to avoid going directly to top level `tensorflow_io/xxx`, as this makes API hard to manage.

(Note `tensorflow_io/gcs` directory was added long time ago and we are in the process of moving it to an underlying directory).

**Comment by marioecd** [comment]
Thanks for the suggestion! Done. I got all the checks passing now.

**Comment by yongtang** [comment]
Thanks @marioecd for the PR!

I will merge the PR to `nightly` branch for now. Once the TF releases another candidate version that include the needed `ParseGcsPath` exposure, I will cherry-pick the commit into master branch.

Note Since TF 2.2.0 is going to be released very soon, and the related commit https://github.com/tensorflow/tensorflow/commit/f303d000c6f5775ce3b609e9a8d8e70e9f8b9252 is not part of TF r2.2 branch, I would assume it will take some time to see the change in master.

On a side note, if https://github.com/tensorflow/tensorflow/commit/f303d000c6f5775ce3b609e9a8d8e70e9f8b9252 could be cherry-picked into TF core's r2.2 branch then this PR could be included in tensorflow/io's master branch really soon.

**Comment by yongtang** [comment]
@marioecd Also, it would be ideal to include a test. A simple python test to make sure at least it does not break when new TF version is released, would be good enough for a start.

**Pull request merged**
