### PR TITLE
Travis CI build enhancements

### PR DESCRIPTION
**Pull request by yongtang**
This PR will try to enhance the Travis CI builds. While Travis CI builds have been very helpful, there are several issues.
- Travis CI only have Ubuntu 14.04 and 16.04 for VM. No Ubuntu 18.04, and 14.04 LTS will not be supported after April.
- The Python version installed by default in Travis CI is not the same as Ubuntu system Python. That triggers issues for 3.6 (https://github.com/tensorflow/io/pull/56#issuecomment-454275394)
- When we release tensorflow-io, we build whl files in docker image `tensorflow/tensorflow:custom-op`. The version of Python does not necessary match, see
  * https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh
  - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_python3.5_pip_packages.sh

- The generated whl files in tensorflow-io was not tested on Ubuntu 16.04 and 18.04.

This PR has the intension of
- [x] Trigger Travis CI to run all unit tests (`Bazel test //tensorflow_io/...`) in `tensorflow/tensorflow:custom-op`, with python versions matching tensorflow ci build.
- [x] Trigger Travis CI to run all unit tests (`Bazel test //tensorflow_io/...`) in Ubuntu 16.04 and 18.04 docker images (not with Travis VM) with system python 2 and 3.
- [x] Trigger Travis CI to build whl files for python 2.7, 3.4, 3.5, 3.6 in `tensorflow/tensorflow:custom-op`, with python matching tensorflow ci build.
- [x] Setup integration/build test to test whl files in Ubuntu 16.04 and 18.04 with system python (added with stub test only now).

The following are the changes in this PR:
- [x] Move top level tf to third_party/tf
- [x] Add -D_GLIBCXX_USE_CXX11_ABI=0 to all third_party C++ libraries as Ubuntu 16.04 and 18.04 may have new C++ compilers
- [x] Add list(range()) in arrow_test.py as otherwise python 3 will not work.
- [x] Use Ubuntu 16.04 for base VM in Travis CI, and move all tests in docker containers to achieve consistency.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
/cc @terrytangyuan @dmitrievanthony to take a look.

Basic story: provide coverage for supported platforms.

When we provide a list of supported platforms, we are talking about several things:
1) The supported platforms when user install from python `tensorflow-io` PyPI.org
2) The supported platforms when user compile `tensorflow-io` from source.
3) The supported platforms when user install from R (CRAN)

In detail:
1) When user install `tensorflow-io` from PyPI.org, they could install with python 2.7, 3.4, 3.5, 3.6. Our position is that `tensorflow-io` support Linux platform that could run `tensorflow`. As such we have to build `tensorflow-io` exactly the same way as `tensorflow` for python 2.7/3.4/3.5/3.6. That is where `customer-op` tests comes from.
2) When user install `tensorflow-io` from PyPI.org, they could install it on a platform different from `custom-op` docker image. Mostly likely user will install `tensorflow-io`/`tensorflow` with system default python on Ubuntu (16.04 and 18.04). So we have to test the binaries of `*.whl` files generated from `customer-op` could run on Ubuntu (16.04 and 18.04) with system-default python.
3) When developer want to build `tensorflow-io` from source, they mostly likely will use a default Ubuntu 16.04/18.04 to compile (with system -default GCC version) so tests also have to be done on those platforms.
4) For R support, users will install `tensorflow-io` from PyPI.org so the binary of `.whl` are actually build from `custom-op`. So we need to test the scenario of building `whl` from `custom-op` docker image, but runs on `Ubuntu + R 3.5`. (@terrytangyuan may have additional input on R)

**Comment by yongtang** [comment]
All tests passes now. I think this PR is ready for review.

**Comment by terrytangyuan** [comment]
@yongtang I changed the travis config for R to this recently: https://github.com/tensorflow/io/blob/e5dc0ebbcf0b8e91f494c6ea69566d5f7d520b10/.travis.yml#L97-L110

This includes the following:
* `language: r` gives more R friendly setup and provides some built-in functionalities besides `devtools::test()` that are otherwise harder to set up ourselves.
* `echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile` configures R to use a specific CRAN mirror
* `--user travis` is needed to get around some permission issues when `language: r` is specified
* The `cache` section significantly speeds up the build

Could you incorporate the above mentioned items in the PR?

**Comment by yongtang** [comment]
@terrytangyuan The PR made changes to CI so now R is tested inside docker containers with Ubuntu 16.04 and 18.04. This is actually different from Travis CI's Ubuntu 14.04 VM and R language spec.

The reason to test inside Ubuntu 16.04 and 18.04 containers is that users are more likely to use Ubuntu 16.04/18.04 than Travis CI's Ubuntu 14.04. (The Ubuntu 14.04 will be out of support in April). Also, Travis CI still hasn't been able to support Ubuntu 18.04 today.

With tests running inside containers some of the optimizations may not be applications. I managed to have the following two in pace in containers:
- echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile configures R to use a specific CRAN mirror
- The directory cache of  $HOME/.cache/pip (by mapping inside and outside of containers) which could speeds up the build

Please take a look and see if it helps.

**Comment by terrytangyuan** [comment]
@yongtang Thanks. That makes sense and the changes look fine to me. I'll probably add the additional work that `language: r` does on Travis later besides `devtools::test()`. The R tests actually failed with:
``` 
Message: AttributeError: 'NoneType' object has no attribute 'video_dataset'
Detailed traceback: 
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 195, in make_one_shot_iterator
    _make_dataset.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 864, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 192, in _make_dataset
    return dataset._as_variant_tensor()  # pylint: disable=protected-access
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2131, in _as_variant_tensor
    self._input_dataset._as_variant_tensor(),  # pylint: disable=protected-access
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_io/video/python/ops/video_dataset_ops.py", line 71, in _as_variant_tensor
    return video_ops.video_dataset(self._filenames)
```
Looks like the exit code of `R -e 'devtools::test()'` wasn't captured properly.

**Comment by yongtang** [comment]
Thanks @terrytangyuan. I updated the PR and the failed R tests on ffmpeg have been fixed. Also changed the check code to `R -e 'stopifnot(all(data.frame(devtools::test())$failed == 0L))'` so that the error exit code could be captured. Please take a look.

**Pull request merged**
