### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by yongtang**
This PR is for the Release of 0.4.0 to match tensorflow 1.13.1. We will see if we want additional contents in.

This is is related to #121.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Oh just realized that other PRs (MNIST, etc) might be included in v0.5.0. Should we hold off on merging those new ops until after v0.5.0 release?

**Comment by yongtang** [comment]
@terrytangyuan I think we could just include mnist in the 0.4.0. The 0.5.0 was the original plan but mnist has been ready anyway. We can just merge mnist, then we release 0.4.0 and see if we could submit to R and pip at the same time in the release?

**Comment by terrytangyuan** [comment]
Okay. Just merged MNIST PR. We still need to add R wrappers for those two new ops though. I'll send a PR soon.

**Comment by terrytangyuan** [comment]
@yongtang Submitted https://github.com/tensorflow/io/pull/123. I didn't update the `R-package/NEWS.md` though. Please add the new op wrappers in this PR.

**Pull request merged**
