### PR TITLE
Add R package documentation website skeleton

### PR DESCRIPTION
**Pull request by terrytangyuan**
This fixes https://github.com/tensorflow/io/issues/26. This only sets up the skeleton so later new tutorials and docs can be added easily. Main changes are in `R-package/pkgdown` and the `*.Rmd` files. The rest of the diff is autogenerated. You can open `R-package/docs/articles/index.html` to explore the website but here are some screenshots for a quick look:

Screen Shot 2019-05-16 at 6 28 54 PM
Screen Shot 2019-05-16 at 6 51 33 PM
Screen Shot 2019-05-16 at 6 28 25 PM
Screen Shot 2019-05-16 at 6 27 07 PM

cc: @yongtang @missaugustina

### CODE REVIEW

**Comment by missaugustina** [comment]
Where would the pkgdown html be hosted?

**Comment by terrytangyuan** [comment]
A follow-up issue would be great! Re the location, I am not sure how this repo is configured and whether we should host in on Github pages or tensorflow website. We could probably discuss it in the mailing list where other people might have a better idea.

**Comment by terrytangyuan** [comment]
@missaugustina Would you like to help initiate a discussion on website hosting and maybe track it in a separate issue?

**Comment by missaugustina** [comment]
@terrytangyuan Yes I can absolutely do that!

**Comment by yongtang** [comment]
@terrytangyuan @missaugustina sorry for the late reply, as I was out of the office last week. The PR looks great! LGTM.

I think we could discuss where to place the doc page (either GitHub or tensorflow.org), probably could send an email to the mailing list?

**Comment by missaugustina** [comment]
> @terrytangyuan @missaugustina sorry for the late reply, as I was out of the office last week. The PR looks great! LGTM.
> 
> I think we could discuss where to place the doc page (either GitHub or tensorflow.org), probably could send an email to the mailing list?

yes, I created the issue but forgot to send email. I will do that now!

**Pull request merged**
