### PR TITLE
adding an option to specify default values for nullable fields in BigQuery connector

### PR DESCRIPTION
**Pull request by vlasenkoalexey**

### CODE REVIEW

**Comment by vlasenkoalexey** [comment]
@sshrdp FYI

**Comment by yongtang** [comment]
@vlasenkoalexey Can you rebase to the latest master branch? I think that will likely solve most of the build failures.

**Comment by vlasenkoalexey** [comment]
I synced branches yesterday, the only commit missing was #1582
Will see if presubmit will pass now

**Review by yongtang — APPROVED** [review]
lgtm

**Comment by vlasenkoalexey** [comment]
Thanks @yongtang, glad that it had made it to the release.

**Pull request merged**
