### PR TITLE
[notebooks] use saved output to prevent site builder issues for elasticsearch.ipynb

### PR DESCRIPTION
**Pull request by kvignesh1420**
This PR addresses the comment: https://github.com/tensorflow/io/issues/1156#issuecomment-721905578 by using the saved outputs to prevent docs builder issues.

Issue reference: https://gist.github.com/MarkDaoust/bd7d027969b0d24b506e690a8d03b7a6#file-elastic-search-new-fail-L111

### CODE REVIEW

**Review by MarkDaoust — CHANGES_REQUESTED** [review]
Test-running this version in the site-builder environment still gives me the same error. 

It works in Colab. 

So I think at this point we should just save the outputs in this notebook so the site builder doesn't need to execute it.

**Comment by kvignesh1420** [comment]
@MarkDaoust thanks for the tests. Can you point me to any reference notebook or any documentation which saves the outputs of cells in the notebook itself? I am not sure about the practices around these fixes. Please let me know.

**Comment by MarkDaoust** [comment]
I just mean open it with colab, and select "runtime > Run all" then when it's done "file > download ipynb", and replace the notebook with the resulting file.

After that the notebook will have "output"s attached to to each code cell.

Here's an example of a file saved that way:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/post_training_float16_quant.ipynb
https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/post_training_float16_quant.ipynb

tensorflow.org shows the saved outputs instead of executing the notebook.

https://www.tensorflow.org/lite/performance/post_training_float16_quant

**Comment by kvignesh1420** [comment]
@MarkDaoust Thanks for the info. I ran all the cells and committed the changes. Updated the PR title and description as well. Please take a look.

**Review by MarkDaoust — APPROVED** [review]
Thanks!

**Pull request merged**
