### PR TITLE
Bump version to tensorflow==2.0.0

### PR DESCRIPTION
**Pull request by yongtang**
Note: This PR will have to :
- Wait for 1.15RC0 is released.
- Then we can create a branch of R0.8 for 1.x support.
- Then this PR is merged to master.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by AlexisBRENON** [comment]
Hi,

I am starting a new ML project and hence start with TF 2.0.
I would like to be able to read Parquet data and thus would rely on tensorflow-io.

Installing it with: `pip install tensorflow-io` complains about TF incompatibility (this is normal) and I cannot import the parquet package with an error about `libtensorflow_framework.so.1` not found. In fact, I have a `libtensorflow_framework.so.2` file in the `tensorflow_core` package.

Thus, I fetch your branch `yongtang:2.0-release`, rebase it onto tensorflow/io:master and try to build from source. Build succeed, I can install the package in my virtualenv (with no warning or error). However, I still cannot import the sub-packages:
```
NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ['.../venv/lib/python3.7/site-packages/tensorflow_io/core/python/ops/libtensorflow_io.so']
caused by: ['libtensorflow_framework.so.2: cannot open shared object file: No such file or directory']
```
However `libtensorflow_framework.so.2` is available at the right place (returned by `tf.sysconfig.get_lib()`).

Can I help to port tensorflow-io to TF2.0?

Thanks.

**Comment by yongtang** [comment]
@AlexisBRENON The PR has been updated and it should work for 2.0 now. To build wheel packages on linux you can run download the PR and run:
```
bash -x -e .travis/python.release.sh
```

That will give you wheel files in `wheelhouse` directory (with 2.7, 3.5, 3.6, 3.7 supported).

We are looking into switch 2.0.0rc0 as the default (as opposed to stick with tf-nightly 1.x) in our nightly build. Related discussion is in https://github.com/tensorflow/io/issues/411#issuecomment-529146101

Also /cc @terrytangyuan @BryanCutler see if switching to 2.0.0rc0 in our nightly build makes sense. We can create a special branch for upcoming TF 1.15 compatible build, and release tensorflow-io 0.8.0 when TF 1.15 is available.

**Comment by terrytangyuan** [comment]
I think it’s okay to switch now at least for nightly builds.

**Comment by yongtang** [comment]
@terrytangyuan @BryanCutler I will merge this PR, and create a special branch R0.8 for v0.8.0 release (match tensorflow==1.15.0).

**Pull request merged**
