### PR TITLE
Add TextInput support

### PR DESCRIPTION
**Pull request by yongtang**
This PR add TextInput support, with expanded archive support.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
The build fail with Ubuntu 16.04 and 18.04, likely caused by the gcc version mismatch of the binary in tensorflow.

The gdb debug shows the segmentation fault happens in `TypeId()` call when marshaling/unmarshaling the Variant type. This is likely similar to #173

**Comment by yongtang** [comment]
Removed building on Ubuntu 16.04 and 18.04 with tensorflow binaries, as it will not work. Our CI is still fully covered, as we build our binary on Ubuntu 14.04, and test on Ubuntu 16.04 and 18.04.

This PR is ready for review.

/cc @terrytangyuan

**Comment by yongtang** [comment]
@terrytangyuan All test finally passed 🎉

**Comment by terrytangyuan** [comment]
Oops seems like there's conflict from the recently merged PR. Could you resolve it?

**Comment by yongtang** [comment]
@terrytangyuan The PR has been rebased and all tests passed now.

**Pull request merged**
