### PR TITLE
fix kafka online-learning section in tutorial notebook

### PR DESCRIPTION
**Pull request by kvignesh1420**
This PR addresses https://github.com/tensorflow/io/issues/1272 by removing the extensive showcase of the online-learning dataset using background threads. 

cc: @MarkDaoust

### CODE REVIEW

**Comment by MarkDaoust** [comment]
Thanks, 

But that doesn't seem to fix it.

Here's a Colab link to your branch for easy testing:

https://colab.sandbox.google.com/github/kvignesh1420/io/blob/kafka-nb/docs/tutorials/kafka.ipynb

This change seems to have moved the error. Now it's generated in the last code cell:

```
def decode_kafka_online_item(raw_message, raw_key):
  message = tf.io.decode_csv(raw_message, [[0.0] for i in range(NUM_COLUMNS)])
  key = tf.strings.to_number(raw_key)
  return (message, key)
  
for mini_ds in online_train_ds:
  mini_ds = mini_ds.shuffle(buffer_size=32)
  mini_ds = mini_ds.map(decode_kafka_online_item)
  mini_ds = mini_ds.batch(32)
  model.fit(mini_ds, epochs=3)

```
```
...
32/32 [==============================] - 0s 4ms/step - loss: 0.4372 - accuracy: 0.8027
Epoch 3/3
32/32 [==============================] - 0s 4ms/step - loss: 0.4257 - accuracy: 0.8027
Epoch 1/3
19/19 [==============================] - 0s 4ms/step - loss: 0.4336 - accuracy: 0.8043
Epoch 2/3
19/19 [==============================] - 0s 4ms/step - loss: 0.4019 - accuracy: 0.8224
Epoch 3/3
19/19 [==============================] - 0s 5ms/step - loss: 0.3998 - accuracy: 0.8191
Epoch 1/3
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-54-4c9022850db6> in <module>()
      8   mini_ds = mini_ds.map(decode_kafka_online_item)
      9   mini_ds = mini_ds.batch(32)
---> 10   model.fit(mini_ds, epochs=3)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1108 
   1109         if logs is None:
-> 1110           raise ValueError('Expect x to be a non-empty array or dataset.')
   1111         epoch_logs = copy.copy(logs)
   1112 

ValueError: Expect x to be a non-empty array or dataset.
```

It looks like the online dataset runs out of data, and returns an empty dataset.

**Comment by kvignesh1420** [comment]
@MarkDaoust yes, I just checked it. `online_train_ds` is returning an empty dataset (`mini_ds`) just before stopping the iteration. Need to check how we can exclude that final empty dataset.

**Comment by kvignesh1420** [comment]
@MarkDaoust I have reduced the `stream_timeout` value to fix this issue as of now. Please check and let me know so that we can finish publishing the docs. I will take a look at the empty dataset generation after this.

**Comment by kvignesh1420** [comment]
@MarkDaoust can you please take a look at this and let me know if it works now?

**Comment by MarkDaoust** [comment]
Testing today, I haven't gotten any new failures. 


Let's merge this.

**Comment by MarkDaoust** [comment]
Published: https://www.tensorflow.org/io/tutorials/kafka

**Pull request merged**
