### PR TITLE
Initial tensorflow-io subsite page setup

### PR DESCRIPTION
**Pull request by yongtang**
This PR is the initial tensorflow-io subsite page setup

Source of some of the yams is from Addons PR: https://github.com/tensorflow/addons/pull/486

/cc @terrytangyuan @BryanCutler @dmitrievanthony @ivelin 

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
I removed the book page for now. We should add the notebook page once we have an initial setup in place.

At the moment it is hard to see what is being rendered. I hope the setup is correct.

**Comment by yongtang** [comment]
/cc @MarkDaoust, I created an initial landing page with book page removed. We can added the book page later.

One issue we are facing is that the page is not rendered so not sure if there are any missing field or values. Can you help take a look if possible?

**Comment by MarkDaoust** [comment]
You will need a `_book.yaml` to set the tabs and table of contents layout.

**Comment by yongtang** [comment]
Thanks @MarkDaoust @lamberta for the help. I updated the PR with _book.yaml page added back, and now _index.yaml pointing to it.

We will work on getting some tutorials in place soon. /cc @terrytangyuan @BryanCutler @ivelin

**Comment by yongtang** [comment]
Also /cc @Ouwen @marcelolerendegui, I saw dicom module in tfio already have an excellent collar notebook:

https://github.com/tensorflow/io/tree/master/tensorflow_io/dicom

Wondering if you are interested in updating the notebook and place it under `docs/tutorials`, then we can point the notebook from tensorflow.org website which should greatly help the user in finding this excellent kernel.

**Comment by MarkDaoust** [comment]
Let's merge this. I'll try staging it this morning. 

I'll report back if there are any changes necessary.

**Comment by yongtang** [comment]
Thanks a lot @MarkDaoust for the help!

**Pull request merged**
