### PR TITLE
PR #510: Add prefix for all implemented ops in .cc modules

### PR DESCRIPTION
**Pull request by ricky3dec**
1. Add prefix to all the ops under tensorflow_io package.
2. Update copyright year.
3. Correct some spaces.

### CODE REVIEW

**Comment by yongtang** [comment]
@ricky3dec Thanks for the PR! It's almost there.

Once the namespace has been added in C++ code, the python code also needs to make small changes to add a prefix `io_` so that it could located the C++ binding correctly.

For example, the following code will need to be updated in Kafka dataset:
```diff
diff --git a/tensorflow_io/kafka/python/ops/kafka_dataset_ops.py b/tensorflow_io/kafka/python/ops/kafka_dataset_ops.py
index 3733857..0ba94ab 100644
--- a/tensorflow_io/kafka/python/ops/kafka_dataset_ops.py
+++ b/tensorflow_io/kafka/python/ops/kafka_dataset_ops.py
@@ -24,7 +24,7 @@ from tensorflow import dtypes
 from tensorflow.compat.v1 import data
 from tensorflow_io.core.python.ops import core_ops
 
-decode_avro = core_ops.decode_avro
+decode_avro = core_ops.io_decode_avro
 
 warnings.warn(
     "implementation of existing tensorflow_io.kafka.KafkaDataset is "
@@ -90,9 +90,9 @@ class KafkaDataset(data.Dataset):
     return []
 
   def _as_variant_tensor(self):
-    return core_ops.kafka_dataset(self._topics, self._servers,
-                                  self._group, self._eof, self._timeout,
-                                  self._config_global, self._config_topic)
+    return core_ops.io_kafka_dataset(self._topics, self._servers,
+                                     self._group, self._eof, self._timeout,
+                                     self._config_global, self._config_topic)
 
   @property
   def output_classes(self):
@@ -120,5 +120,5 @@ def write_kafka(message,
   Returns:
       A `Tensor` of type `string`. 0-D.
   """
-  return core_ops.write_kafka(
+  return core_ops.io_write_kafka(
       message=message, topic=topic, servers=servers, name=name)
```

**Comment by ricky3dec** [comment]
@yongtang , sure I would look into that and send another PR.

One more thing, I have not modified the existing namespaces in classes and just renamed the ops with a prefix and also updated it's usage elsewhere. Also I have not modified the instances of "REGISTER_FILE_SYSTEM"  or "REGISTER_UNARY_VARIANT_DECODE_FUNCTION" which I found in "ggfs_ops.cc" and  "cifar_input.cc". Please let me know if those have to be modified as well?

**Comment by yongtang** [comment]
@ricky3dec I will take another look but I think we could leave them alone for now. Thanks for your great work!

**Comment by yongtang** [comment]
All tests pass except for `io_audio_input = _ffmpeg_ops.audio_input`. This is a huge PR so I will just merge (to avoid merge conflict in case other PR merge), and create a follow up PR to cover the remaining issue.

Thanks @ricky3dec for your great effort, and 🎉 to your contribution!

**Comment by ricky3dec** [comment]
> All tests pass except for `io_audio_input = _ffmpeg_ops.audio_input`. This is a huge PR so I will just merge (to avoid merge conflict in case other PR merge), and create a follow up PR to cover the remaining issue.
> 
> Thanks @ricky3dec for your great effort, and 🎉 to your contribution!

Thanks @yongtang for your support! Looking forward to more such contributions :-)

**Pull request merged**
